const dataMasters = [
	{
		id: '1',
		title: 'Перукар',
		subTitle1: 'Нарощування нігтів',
		subTitle2: 'Нарощування нігтів',
		subTitle3: 'Нарощування нігтів',
		subTitle4: 'Нарощування нігтів',
		subTitle5: 'Нарощування нігтів',
		subTitle6: 'Нарощування нігтів',
		name: 'Анна',
		avatar: require("../../components/MastersF/Image/CI1.png"),
		alt: 'avatars of the masters',
		image1: require("../../components/MastersF/Image/MP1.jpg"),
		image2: require("../../components/MastersF/Image/MP2.jpg"),
		image3: require("../../components/MastersF/Image/MP3.jpg"),
		image4: require("../../components/MastersF/Image/MP4.jpg"),
		image5: require("../../components/MastersF/Image/MP5.jpg"),
		image6: require("../../components/MastersF/Image/MP6.jpg"),
		text1: 'Щоб підтримувати високу конкурентну здатність незважаючи на зростання зарплат, уряд заохочує до діяльності по додаванню вартості в промисловості та обслуговуванню.',
		text2: 'Щоб підтримувати високу конкурентну здатність незважаючи на зростання зарплат, уряд заохочує до діяльності по додаванню вартості в промисловості та обслуговуванню.',
		text3: 'Щоб підтримувати високу конкурентну здатність незважаючи на зростання зарплат, уряд заохочує до діяльності по додаванню вартості в промисловості та обслуговуванню.',
		text4: 'Щоб підтримувати високу конкурентну здатність незважаючи на зростання зарплат, уряд заохочує до діяльності по додаванню вартості в промисловості та обслуговуванню.',
		text5: 'Щоб підтримувати високу конкурентну здатність незважаючи на зростання зарплат, уряд заохочує до діяльності по додаванню вартості в промисловості та обслуговуванню.',
		text6: 'Щоб підтримувати високу конкурентну здатність незважаючи на зростання зарплат, уряд заохочує до діяльності по додаванню вартості в промисловості та обслуговуванню.',
		altImage: 'examples of work',
	},
	{
		id: '2',
		title: 'Манікюр',
		name: 'Елена',
		avatar: require("../../components/MastersF/Image/CI2.png"),
		alt: 'avatars of the masters',
		image1: require("../../components/MastersF/Image/MM1.jpg"),
		image2: require("../../components/MastersF/Image/MM2.jpg"),
		image3: require("../../components/MastersF/Image/MM3.jpg"),
		image4: require("../../components/MastersF/Image/MM4.jpg"),
		image5: require("../../components/MastersF/Image/MM5.jpg"),
		image6: require("../../components/MastersF/Image/MM6.jpg"),
		altImage: 'examples of work',
	},
	{
		id: '3',
		title: 'Педикюр',
		name: 'Розанна',
		avatar: require("../../components/MastersF/Image/CI3.png"),
		alt: 'avatars of the masters',
		image1: require("../../components/MastersF/Image/MPP1.jpg"),
		image2: require("../../components/MastersF/Image/MPP2.jpg"),
		image3: require("../../components/MastersF/Image/MPP3.jpg"),
		image4: require("../../components/MastersF/Image/MPP4.jpg"),
		image5: require("../../components/MastersF/Image/MPP5.jpg"),
		image6: require("../../components/MastersF/Image/MPP6.jpg"),
		altImage: 'examples of work',
	},
	{
		id: '4',
		title: 'Косметолог',
		name: 'Вера',
		avatar: require("../../components/MastersF/Image/CI4.png"),
		alt: 'avatars of the masters',
		image1: require("../../components/MastersF/Image/MK1.jpg"),
		image2: require("../../components/MastersF/Image/MK2.jpg"),
		image3: require("../../components/MastersF/Image/MK3.jpg"),
		image4: require("../../components/MastersF/Image/MK4.jpg"),
		image5: require("../../components/MastersF/Image/MK5.jpg"),
		image6: require("../../components/MastersF/Image/MK6.jpg"),
		altImage: 'examples of work',
	},
	{
		id: '5',
		title: 'Масажист',
		name: 'Леся',
		avatar: require("../../components/MastersF/Image/CI5.png"),
		alt: 'avatars of the masters',
		image1: require("../../components/MastersF/Image/MF1.jpg"),
		image2: require("../../components/MastersF/Image/MF2.jpg"),
		image3: require("../../components/MastersF/Image/MF3.jpg"),
		image4: require("../../components/MastersF/Image/MF4.jpg"),
		image5: require("../../components/MastersF/Image/MF5.jpg"),
		image6: require("../../components/MastersF/Image/MF6.jpg"),
		altImage: 'examples of work',
	},
	{
		id: '6',
		title: 'Візаж',
		name: 'Тетяна',
		avatar: require("../../components/MastersF/Image/CI6.png"),
		alt: 'avatars of the masters',
		image1: require("../../components/MastersF/Image/MV1.jpg"),
		image2: require("../../components/MastersF/Image/MV2.jpg"),
		image3: require("../../components/MastersF/Image/MV3.jpg"),
		image4: require("../../components/MastersF/Image/MV4.jpg"),
		image5: require("../../components/MastersF/Image/MV5.jpg"),
		image6: require("../../components/MastersF/Image/MV6.jpg"),
		altImage: 'examples of work',
	},
];

export default dataMasters;