const ADD_COMMENT = 'ADD-COMMENT';
const UPDATE_NEW_COMMENT_TEXT = 'UPDATE-NEW-COMMENT-TEXT';

let store = {
	_data: {
		dataBlog: [
			{
				id: 'topic1',
				title: 'Лазерна епіляція',
				header: 'Як підготуватись до процедури лазерної епіляції?',
				text: 'Ті зони, де проводитиметься процедура лазерної епіляції, потрібно поголити за 4 – 8 годин до процедури, щоб не було щетини. Таким чином, процедура лазерної епіляції буде максимально безболісною та ефективною.',
			},
			{
				id: 'topic2',
				title: 'Лазерна епіляція',
				header: 'Який догляд за шкірою після процедури лазерної епіляції?',
				text: 'Після процедури не можна 2 тижні засмагати, відвідувати солярій, відвідувати сауни, лазні, басейни, приймати гарячу ванну, а також протягом трьох днів після процедури лазерної епіляції на оброблені ділянки шкіри наносити ввечері Пантенол або Бепантен.',
			},
			{
				id: 'topic3',
				title: 'Лазерна епіляція',
				header: 'Який лазер використовується у Салоні?',
				text: 'Laser 22 зупинив свій вибір на діодному американському лазері Lumenis Light Sheer ET, тому що цей лазер - схвалений американською асоціацією FDA, яка є найсуворішою організацією у своїх вимогах щодо сертифікації медичних технологій, та виявив себе на практиці, як найефективніший лазер з видалення волосся і продовжує бути лідером серед усіх апаратів для лазерної епіляції.',
			},
			{
				id: 'topic4',
				title: 'Волосся',
				header: 'Як вибрати і де придбати професійні засоби по догляду за волоссям?',
				text: 'Погана екологія, нездоровий спосіб життя, нестача вітамінів і мінералів в щоденному раціоні дуже згубно впливають на стан наших волосся. Якщо додати до цього списку постійну сушіння гарячим феном і використання засобів для укладання, то стає зрозумілим, чому більшості жінок необхідна професійна косметика для волосся під час щоденного догляду. Найчастіше тільки професійні засоби для волосся здатні повернути волоссю здоров\'я, шовковистість, природну м\'якість і блиск.',
			},
			{
				id: 'topic5',
				title: 'Косметологія',
				header: 'З якого віку рекомендується мезотерапія?',
				text: 'Вік залежить від розв\'язуваної проблеми. Якщо ми намагаємося лікувати якесь захворювання, то можна застосовувати мезотерапевтический метод введення препаратів практично з 18-річного віку. Частота процедур - один-два курси на рік для омолодження. Невблаганне наближення віку сорокаріччя у більшості жінок викликає занепокоєння і навіть паніку. Звичайно, щоб добре виглядати в 40 років, слід починати замислюватися про турботу про свою шкірі ще з 25 років, доглядати за обличчям, шиєю і областю декольте, приділяти увагу своєму зовнішньому вигляду. Омолодження обличчя в 40 років стане набагато результативніше, якщо всі ці роки жінка належним чином дбала про свою шкіру.',
			},
			{
				id: 'topic6',
				title: 'Косметологія',
				header: 'Чи правда те, що ін\'єкції БОТОКС можуть відучити від шкідливої звички хмуритися?',
				text: 'З\'явитися вони можуть і в 18 років – зазвичай тому, що ви щурітесь на сонці, хмурите брови на роботі або морщите лоб, коли смієтеся. Ваша зовнішність не змінюється. Просто корекція зморшок за допомогою введення Ботокса або Диспорту дозволяє вам виглядати молодше. При тому що Ботокс зберігає міміку обличчя. Ефект від уколів Ботоксу (Botox) і Диспорту (Dysport) триває 4-6 місяців. Після цього мімічні зморшки повертаються в початковий стан. І перед вами постає вибір: або залишити все, як є, або повторити процедуру корекції зморшок і зробити Ботокс знову. Повторні ін\'єкції Ботокса часто забезпечують триваліший ефект, ніж перші. ',
			},
			{
				id: 'topic7',
				title: 'Косметологія',
				header: 'Яку вибрати і де краще придбати косметику для обличчя?',
				text: 'Щоб правильно підібрати косметичні засоби, в першу чергу потрібно визначити, який у вас тип шкіри! Для визначення типу шкіри обов\'язково проконсультуйтеся у професійного косметолога, так як і суха і жирна шкіра має свої, візуально визначаються характеристики. Існує також змішаний тип шкіри і чутлива шкіра обличчя. У випадку з проблемною шкірою питання пошуку засобів догляду за проблемною шкірою може бути вирішений лише шляхом ретельного вибору. Такий вибір допоможуть зробити фахівці косметологи.',
			},
			{
				id: 'topic8',
				title: 'Косметологія',
				header: 'Хто такий косметолог?',
				text: 'Косметологія- (від грецького κοσμητικός, kosmētikos, «кваліфікований у прикрасі» і - λογία,-logia-«вчення») наука про красу. - фахівець, що займається вивченням догляду за обличчям і тілом, а також методів, засобів призначених його підтримувати в прекрасній формі. Косметолог рекомендує засоби по догляду за шкірою, розповідає як піклуватися про проблемні зони. У нашій країні людина без білого халата (і відповідних скоринок) косметологом працювати не може, цією справою займаються тільки громадяни з медичною освітою!',
			},
			{
				id: 'topic9',
				title: 'Волосся',
				header: 'Плюси і мінуси при виборі домашнього або салонного фарбування волосся?',
				text: 'Пропонуємо Вам розібратися в явно хвилює багатьох питанні щодо підрозділи фарб на професійні та непрофесійні. Мова йде про фарбування волосся, як правило, в салонах краси, в першому випадку, і про фарбування в домашніх умовах – у другому. Слід спочатку відзначити, що професійні фарби для волосся не продаються в звичайних магазинах, так як виробники наполягають на поширення тільки в салонах краси та перукарнях. Також перукар звертає увагу на проявляється в процесі фарбування результат і вносить корективи по ходу процесу.',
			},
			{
				id: 'topic10',
				title: 'Косметологія',
				header: 'Як розшифрувати дату виробництва косметики?',
				text: 'Дата виробництва зашифрована спеціальним чином і може бути нанесена на картонну упаковку, сполучний шов туби, дно скляної або пластикової баночки. Для засобів домашньої лінії, як правило, шифр виглядає наступним чином: ГММПП, де Г – остання цифра року виробництва; ПП – номер партії. На деяких артикулах професійної лінії і на ампульною продукції шифр виглядає по-іншому, і тоді за його розшифровкою слід звернутися до вашого косметолога.',
			},
		],
		dataGoods: [
			{
				id: 'Shampoo1',
				article: '123456789',
				name: 'Безсульфатний шампунь з кератином, 150 мл',
				description: 'La\'dor Keratin LPP Shampoo Шампунь для волосся з кератином безсульфатний, 150 мл - унікальний засіб для салонного догляду за волоссям. Безсульфатний шампунь працює в двох напрямках - дбайливо очищає волосся без участі шкідливих речовин і при цьому насичує локони кератином, відновлюючи їх структуру. Як відомо, кератин - це будівельний матеріал для локонів і при його втраті вони стають ламкими, сухими і тьмяним. Шампунь з кератином заповнює «порожнечі» у волоссі і тим самим реконструює їх. Крім того, відсутність шкідливих сульфатів, парабенів і силіконів в складі продукту сприятливо впливає на здоров\'я локонів. Так, безсульфатний шампунь не піниться так, як звичайний, але не варто цього боятися. Засіб ефективно очищає шкіру голови і волосся, не травмуючи їх. Ще одна перевага кератинового шампуню від La\'dor - він збагачений натуральними амінокислотами, протеїнами шовку та розкішним коктейлем їз різних масел (лаванди, камелії, жожоба, авокадо, Аргана, евкаліпта). Весь цей комплекс корисних речовин робить шампунь не тільки засобом для очищення, а й одним з етапів ефективного лікування волосся.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови і коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
				composition: 'Water, Cocoamidopropyl Betaine, Disodium Laureth Sulfosuccinate, lauramine oxide, Glycerine, Butylene Glycol, TEA-Cocoyl Glutamate, Cocamide DEA, PEG-120 Methyl Glucose Dioleate, PPG-3 Caprylyl Ether, PEG-7 Glyceryl Cocoate, Betaine, Hydroxypropyl Chitosan , Trehalose, Hydrolyzed Wheat Protein, Hydrolized Corn Protein, Hydrolized Soy Protein, Hydrolyzed Silk, Sodium Hyaluronate, Dipropylene Glycol, Zein, Argania Spinosa Kernel Oil, Avocado Oil, Camellia Japonica Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Citric Acid, Polyquaternium-10, Hydroxyacetophenone, Sodium Benzoate, Fragrance.',
				prise: 275,
				image: require("./img/Goods/1g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo2',
				article: '123456798',
				name: 'Шампунь для сухого і нормального волосся безсульфатний, 530 мл',
				description: 'La\'dor Keratin LPP Shampoo Шампунь для сухого і нормального волосся безсульфатний, 530 мл - шампунь для професійного догляду за шкірою голови та волоссям, який ви можете використовувати в домашніх умовах. Працює одночасно у двох напрямках - делікатно очищає і відновлює локони. Не містить шкідливі сульфати, парабени й силікони.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
				composition: 'Water, Cocoamidopropyl Betaine, Disodium Laureth Sulfosuccinate, lauramine oxide, Glycerine, Butylene Glycol, TEA-Cocoyl Glutamate, Cocamide DEA, PEG-120 Methyl Glucose Dioleate, PPG-3 Caprylyl Ether, PEG-7 Glyceryl Cocoate, Betaine, Hydroxypropyl Chitosan, Trehalose, Hydrolyzed Wheat Protein, Hydrolized Corn Protein, Hydrolized Soy Protein, Hydrolyzed Silk, Sodium Hyaluronate, Dipropylene Glycol, Zein, Argania Spinosa Kernel Oil, Avocado Oil, Camellia Japonica Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Citric Acid, Polyquaternium- 10, Hydroxyacetophenone, Sodium Benzoate, Fragrance.',
				prise: 699,
				image: require("./img/Goods/2g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Fill3',
				article: '123456978',
				name: 'Філер для волосся відновлюючий, 4*13 мл',
				description: 'Lador Perfect Hair Fill-Up Корейський філер для волосся, 4*13 мл - миттєво повертає пошкодженому волоссю структурну цілісність, еластичність й шовковистість. Отриманий ефект ламінування волосся за якістю не відрізняється від салонного результату. Корейський філер для волосся від Lador моментально проникає всередину волосяного стрижня, згладжує лусочки, заповнює порожнечі та пошкодженні структури, повертає волоссю гладкість і здоровий блиск. Філер нормалізує PH, відновлює волосся, ослаблені фарбуванням і хімічними завивками.',
				forWhat: 'відновлення',
				type: 'філер',
				application: 'вміст ампули змішати з холодною водою в пропорції 1: 1. Використовувати тільки керамічну місткість. Ретельно перемішати рідину і нанести отриманий склад на чисте, сухе волосся по всій довжині. Залишити на 15-20 хвилин. Для кращого ефекту використовувати термошапочку або прогріти феном. Змити теплою водою.',
				composition: ' Alcohol, Propylene Glycol, Cetrimonium Chloride, Benzyl Glycol, Ethylhexylglycerin, Raspberry Ketone, Hydrolyzed Keratin, Hydrolyzed Collagen, Hydrolyzed Silk, Ceramide NP, PEG-12 Dimethicone, Glycerin, Octyldodeceth-20, Octyldodeceth-16, Glyoxyloyl Carbocysteine, Glyoxyloyl Keratin Amino Acids, Butylene Glycol, Phyllanthus Emblica Extract, Polyquaternium-92, Citric Acid, Fragrance',
				prise: 380,
				image: require("./img/Goods/3g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Fill4',
				article: '193456978',
				name: 'Філер для волосся відновлюючий, 13 мл',
				description: 'Lador Perfect Hair Fill-Up Корейський філер для волосся, 13 мл - миттєво повертає пошкодженому волоссю структурну цілісність, еластичність й шовковистість. Отриманий ефект ламінування волосся за якістю не відрізняється від салонного результату. Корейський філер для волосся від Lador моментально проникає всередину волосяного стрижня, згладжує лусочки, заповнює порожнечі та пошкодженні структури, повертає волоссю гладкість і здоровий блиск. Філер нормалізує PH, відновлює волосся, ослаблені фарбуванням і хімічними завивками.',
				forWhat: 'відновлення',
				type: 'філер',
				application: 'вміст ампули змішати з холодною водою в пропорції 1: 1. Використовувати тільки керамічну місткість. Ретельно перемішати рідину і нанести отриманий склад на чисте, сухе волосся по всій довжині. Залишити на 15-20 хвилин. Для кращого ефекту використовувати термошапочку або прогріти феном. Змити теплою водою.',
				composition: ' Alcohol, Propylene Glycol, Cetrimonium Chloride, Benzyl Glycol, Ethylhexylglycerin, Raspberry Ketone, Hydrolyzed Keratin, Hydrolyzed Collagen, Hydrolyzed Silk, Ceramide NP, PEG-12 Dimethicone, Glycerin, Octyldodeceth-20, Octyldodeceth-16, Glyoxyloyl Carbocysteine, Glyoxyloyl Keratin Amino Acids, Butylene Glycol, Phyllanthus Emblica Extract, Polyquaternium-92, Citric Acid, Fragrance',
				prise: 80,
				image: require("./img/Goods/4g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo5',
				article: '133456978',
				name: 'Шампунь з амінокислотами, 400 мл',
				description: 'Lador Herbalism Shampoo Шампунь з амінокислотами, 400 мл. Шампунь направлений заспокоює шкіру голови і освіжає її, а також живить пошкоджене волосся. Містить 7 трав’яних екстрактів, які зміцнюють волосся, заспокоюють і оздоровлюють шкіру голови. 20 видів амінокислот працюють на живлення і відновлення пошкодженого волосся. Шампунь не містить силіконів, дарує м’якість і блиск.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'на вологе волосся нанести потрібну кількість шампуню, помасувати, ретельно змити, за потреби повторити.',
				composition: 'water, sodium C14-16 olefinsulfonate, coco-betaine, glycerin, butylene glycol, decyl glucoside, MEA cocamide, caprylhydroxamic acid, methylpropanediol, cinanhuma extract, hydroxypropyltrimonium chloride, guarodium hydroxypropyltrimonium chloride, panthenol, salicylic acid, citric acid, EDTA disodium, niacinamide, ethylhexylglycerin, arginine, leucine, tryptophan, lizin, threonine, methionine, hydride stidine, asparagine, allanine, proline, glutamic acid, glutamine, glycine, valine, phenylalanine, aspartic acid, tyrosine, serine, cystine, rhemania root extract, lycarian dogwood extract, Japanese dioscorea root extract, aquatic plantain bulby extract, coconut porium extract, pivonia root extract, witch hazel leaf extract, sage leaf extract, melisi liquor leaf extract, pepper juice extract, lavender flower extract, hautunii extract, eucalyptus globulus leaf extract, soy bean extract.',
				prise: 699,
				image: require("./img/Goods/5g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo6',
				article: '133486978',
				name: 'Шампунь для волосся на основі трав\'яних екстрактів, 150 мл',
				description: 'Lador Herbalism Shampoo Шампунь для волосся на основі трав\'яних екстрактів, 150 мл - відмінний продукт для глибокого очищення і зволоження шкіри голови та волосся. 7 трав\'яних екстрактів в основі складу зміцнюють волосяні цибулини, стимулюють кровообіг шкіри голови, живлять волосся корисними мікроелементами. 20 видів амінокислот живлять волосся, відновлюють пошкоджену структуру. Професійний догляд за волоссям це завжди відмінний вибір, тому що результат після застосування завжди відповідає вашим очікуванням.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанести засіб на корені волосся, легкими, масажними рухами розтерти по шкірі голови, змити теплою водою.',
				composition: 'Water, Sodium C14-16 Olefinsulfonate, Coco-Betaine, Glycerin, Butylene Glycol, Decyl Glucoside, MEA Cocamide, Caprilhydroxamic Acid, Methylpropanediol, Cinanhuma Extract, Hydroxypropyltriol Guaric Hydroxypropyltrimonium Chloride, Panthenol, Salicylic Acid, Citric Acid, Sodium EDTA, Niacinamide, Ethylhexylglycerin, Arginine, Leucine, Tryptophan, Lizine, Isoleucine, Threionine Methionine, Histidine, Asparagine, Alanine, Proline, Glutamic Acid, Glutamine, Glycine, Valine, Phenylalanine, Aspartic Acid, Tyrosine, Serine, Cystine, Root Extract, Likarsky Dogwood Extract, Japanese Dioskor Root Extract, Water Plantain Bulby Extract, Coconut Leek Extract, Pivonia Root Extract, Hamamelis Listieu Extract, Sage Leaf Extract, Sage Extract.',
				prise: 305,
				image: require("./img/Goods/6g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Mask7',
				article: '123486978',
				name: 'Маска для волосся на основі трав\'яних екстрактів, 360 мл',
				description: 'Lador Herbalism Treatment Маска для волосся на основі трав\'яних екстрактів, 360 мл - відмінний продукт для відновлення і зволоження волосся від впливу агресивних факторів зовнішнього середовища. Маска розрахована на глибоке живлення і зволоження. 7 трав\'яних екстрактів в основі складу зміцнюють волосяні цибулини, стимулюють кровообіг шкіри голови, живлять волосся корисними мікроелементами. 20 видів амінокислот живлять волосся, відновлюють пошкоджену структуру. Молочна кислота відновить мікрофлору шкіри голови, стимулює ріст волосся.',
				forWhat: 'зволоження і живлення',
				type: 'маска',
				application: 'нанести засіб на чисте вологе волосся, потримати 10-15 хвилин, потім змити теплою водою.',
				composition: 'Water, Sodium C14-16 Olefinsulfonate, Coco-Betaine, Glycerin, Butylene Glycol, Decyl Glucoside, MEA Cocamide, Caprilhydroxamic Acid, Methylpropanediol, Cinanhuma Extract, Hydroxypropyltriol Guaric Hydroxypropyltrimonium Chloride, Panthenol, Salicylic Acid, Citric Acid, Sodium EDTA, Niacinamide, Ethylhexylglycerin, Arginine, Leucine, Tryptophan, Lizine, Isoleucine, Threionine Methionine.',
				prise: 865,
				image: require("./img/Goods/7g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Mask8',
				article: '123486998',
				name: 'Маска для волосся на основі трав\'яних екстрактів, 150 мл',
				description: 'Lador Herbalism Treatment Маска для волосся на основі трав\'яних екстрактів, 150 мл - відмінний продукт для відновлення і зволоження волосся від впливу агресивних факторів зовнішнього середовища. Маска розрахована на глибоке живлення і зволоження. 7 трав\'яних екстрактів в основі складу зміцнюють волосяні цибулини, стимулюють кровообіг шкіри голови, живлять волосся корисними мікроелементами. 20 видів амінокислот живлять волосся, відновлюють пошкоджену структуру. Молочна кислота відновить мікрофлору шкіри голови, стимулює ріст волосся.',
				forWhat: 'зволоження і живлення',
				type: 'маска',
				application: 'нанести засіб на чисте вологе волосся, потримати 10-15 хвилин, потім змити теплою водою.',
				composition: 'Water, cethearilovi alcohol, Propipringle, Amnopropy Dimethicon, C13-15 Alcana, Steatrimoni Chlorid, Dimethicon, Cetrimoni Chlorid, Cetylovius Alcohol, Stearamid Ekstrak Ekhpertil Dimetiliye-7, Amodinniytni Vinograd, Oil Nasiynni Vinograd, Oil Kotrok of Argan, Glizeril Ekrak Eviye ',
				prise: 389,
				image: require("./img/Goods/8g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Balm9',
				article: '123466998',
				name: 'Бальзам для пошкодженого волосся з протеїнами шовку, 200 мл',
				description: 'La\'dor Wonder Balm Бальзам для пошкодженого волосся з протеїнами шовку, 200 мл - ефективний засіб для професійного догляду за волоссям від люксового корейського бренду. Експрес-бальзаму знадобиться менше ніж хвилину, щоб зволожити волосся від коренів до кінчиків і помітно перетворити їх. Його можна застосовувати як SOS-засіб перед важливими заходами, при сильному пошкодженні локонів і на постійній основі в якості одного з етапів догляду. ',
				forWhat: 'зволоження і живлення',
				type: 'бальзам',
				application: 'для експрес-догляду нанесіть невелику кількість кондиціонера на попередньо вимите волосся, відступаючи від кореня. Залиште на волоссі на 1 хвилину і змийте теплою водою. Для інтенсивного впливу бальзам можна залишати на 5-10 хвилин. Використовувати 1-2 рази в тиждень.',
				composition: 'Water, Hydrolyzed Silk, Cetearyl Alcohol, Butylene Glycol, Propylene Glycol, Glycerin, Behentrimonium Chloride, Dimethicone, Macadamia Ternifolia Seed Oil, Phytantriol, Aloe Barbadensis Leaf Extract, Ceramide NP, Sodium Benzoate, Arginine, Leucine, Tryptophan, Lysine, Isoleucine, Threonine, Methionine, Histidine, Asparagine, Alanine, Proline, Glutamic Acid, Glutamine, Glycine, Valine, Phenylalanine, Aspartic Acid, Tyrosine, Serine, Cystine, Benzyl Benzoate, Benzyl Salicylate, Citronellol, Geraniol, Hexyl Cinnamal, Limonene, Linalool, Fragrance\n' +
					'\n',
				prise: 735,
				image: require("./img/Goods/9g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Balm10',
				article: '113466998',
				name: 'Бальзам-маска для волосся з протеїнами шовку, 250 мл',
				description: 'La\'dor Wonder Tear Бальзам-маска для волосся з протеїнами шовку, 250 мл - універсальний засіб для локонів, що працює відразу в трьох напрямках: зміцнює волосся, зволожує їх і надає їм помітний об\'єм. Бальзам-маска не вимагає довгих маніпуляцій і може значно поліпшити стан волосся менше ніж за 1 хвилину. Варто зазначити, що цей продукт застосовують для професійного догляду, тому ви можете отримати ефект справжньої салонної процедури в домашніх умовах. \n' +
					'\n',
				forWhat: 'зволоження і живлення',
				type: 'маска',
				application: 'для експрес-догляду нанесіть невелику кількість продукту на попередньо вимите волосся, відступаючи від кореня. Залиште на волоссі на 1 хвилину і змийте теплою водою. Для інтенсивного впливу бальзам-маску можна залишати на 5-10 хвилин. Використовувати 1-2 рази в тиждень.',
				composition: 'Water, Dimethicone, Cetearyl Alcohol, Behentrimonium Chloride, Butylene Glycol, Propylene Glycol, Amodimethicone, C12-14 Sec-Pareth-7, Hydrolyzed Silk, Aloe Barbadensis Leaf Extract, Ceramide NP, Arginine, Leucine, Tryptophan, Lysine, Isoleucine, Threonine, Methionine, Histidine, Asparagine, Alanine, Proline, Glutamic Acid, Glutamine, Glycine, Valine, Phenylalanine, Aspartic Acid, Tyrosine, Serine, Cystine, Benzyl Benzoate, Benzyl Salicylate, Hexyl Cinnamal, Linalool, Fragrance\n' +
					'\n',
				prise: 849,
				image: require("./img/Goods/10g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo11',
				article: '113496998',
				name: 'Шампунь проти випадіння з ментолом для всіх типів волосся, 530 мл',
				description: 'La\'dor Dermatical Hair Loss Shampoo Шампунь проти випадіння з ментолом для всіх типів волосся, 530 мл - професійний засіб від всесвітньо відомого корейського бренду відмінно заспокоює шкіру голови та очищає волосся. Головна мета шампуню - боротьба з надмірним випаданням локонів і стимуляція їх зростання. Шампунь не містить сульфатів, силіконів, штучних барвників, ароматизаторів і має нейтральний pH. Особливий бонус - шампунь дає холодок, освіжає і смачно пахне цитрусами.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити',
				composition: 'Water, Lauryl Glucoside, Decyl Glucoside, Cocodimonium Hydroxypropyl Hydrolyzed Wheat Protein Polyquaternium-10, Disodium Cocoyl Glutamate, Sodium Cocoyl Glutamate, L-Menthol, Salicylic Acid, Dexpanthenol, 1,2-Hexanediol, Propylene Glycol, Hyaluronic Acid, Citrus Aurantium Dulcis (Orange) Oil, Lavandula Angustifolia (Lavender) Oil, Cymbopogon Schoenanthus Oil, Abies Sibirica Oil, Amyris Balsamifera Bark Oil, Salvia Sclarea (Clary) Oil, Sophora Flavescens Root Extract, Capsicum Annuum Fruit Extract, Lycium Chinense Fruit Extract',
				prise: 999,
				image: require("./img/Goods/11g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Conditioner12',
				article: '113496999',
				name: 'Кондиціонер для сухого та пошкодженого волосся зволожуючий без силіконів, 530 мл',
				description: 'La\'dor Moisture Balancing Conditioner Кондиціонер для сухого та пошкодженого волосся зволожуючий без силіконів, 530 мл - професійний засіб для інтенсивного зволоження сухого та ламкого волосся, пошкоджених фарбуваннями і укладаннями. Кондиціонер збагачений комплексом натуральних інгредієнтів і не містить шкідливих силіконів.',
				forWhat: 'зволоження і живлення',
				type: 'кондиціонер',
				application: 'нанесіть невелику кількість кондиціонера на попередньо вимите волосся, відступаючи від кореня. Залиште на волоссі на кілька хвилин. Змийте теплою водою.',
				composition: 'Water, Cetearyl Alcohol, Behenyl Trimethyl Ammonium Chloride, Paraffin Wax,Glycerin, PPG-3 Caprylyl Ether, Butylene Glycol, Saponaria Officinalis Leaf Extract, Lavandula Angustifolia (Lavender) Flower Extract, Monarda Didyma Leaf Extract, Mentha Piperita (Peppermint) Leaf Extract',
				prise: 609,
				image: require("./img/Goods/12g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo13',
				article: '123496999',
				name: 'Шампунь для сухого волосся органічний безсульфатний, 530 мл',
				description: 'La\'dor Triplex Natural Shampoo Шампунь для сухого волосся органічний безсульфатний, 530 мл - професійний шампунь, дбайливо очищає без застосування агресивних і шкідливих компонентів. Тільки натуральний миючі інгредієнти та корисні олії в складі. Продукт не викликає подразнень, не сушить, не сплутує волосся і підходить для чутливої ​​шкіри голови. Формула шампуню містить олії лаванди та чайного дерева, екстракт лимона і куркуму, які мають антибактеріальну властивості, живлять і зволожують волосся, роблять їх слухняними та блискучими. Рослинні компоненти знімають свербіж, усувають лупу і нормалізують кислотно-лужний баланс. Засіб не містить шкідливі сульфати, парабени й силікони',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
				composition: 'Water, Lauryl Glucoside, Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, TEA-Cocoyl Glutamate, Sodium Chloride, Citric Acid, Hydroxyacetophenone, Polyquaternium-7, Polyquaternium-10, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Olea Europaea (Olive) Fruit Oil, Ribes Nigrum (Black Currant) Leaf Extract, Curcuma Longa (Turmeric) Root Extract, Zanthoxylum Schinifolium Leaf Extract, Pulsatilla Koreana Extract',
				prise: 789,
				image: require("./img/Goods/13g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Mask14',
				article: '123496499',
				name: 'Маска для екстра-відновлення пошкодженого волосся колагенова, 150 мл',
				description: 'La\'dor Eco Hydro LPP Treatment Маска для екстра-відновлення пошкодженого волосся колагенова, 150 мл - маска, створена для реанімації сухого і пошкодженого волосся після фарбувань і хімзавивок. Швидко, навіть з першого застосування, живить волосся, прибирає ламкість і тьмяність, робить їх м\'якими та блискучим як шовк. Варто зазначити, що цей продукт відноситься до професійних і є повноцінним салонним доглядом в домашніх умовах. В основі маски - колаген, який швидко робить локони пружними, усуває сухість і ефективно бореться з посічені кінчиками. Доповнено засіб екстрактом моркви, зміцнює волосяні фолікули та маслами жожоба й оливи, які наповнюють їх вітамінами.',
				forWhat: 'зволоження і живлення',
				type: 'маска',
				application: 'нанесіть невелику кількість маски на попередньо вимите волосся, відступаючи від кореня. Залиште на волоссі на кілька хвилин. Змийте теплою водою.',
				composition: 'Water, Cetearyl Alcohol, Benzyl Alcohol, Olea Europaea (Olive) Fruit Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Oleyl Alcohol, Daucus Carota Sativa (Carrot) Root Extract, Stearamidopropyl Dimethylamine, Citric Acid, Lactic Acid, Benzophenone-9, Hydrolyzed Collagen, C12-18 Dialkyldimonium Chloride, Panthenol, Benzyl Glycol, Ethylhexylglycerin, Raspberry Ketone, Glycerin, Octyldodeceth-20, Octyldodeceth-16, Fragrance, Benzyl Salicylate, Cinnamyl Alcohol, Citronellol, Geraniol, Hexyl Cinnamal, Hydroxycitronellal',
				prise: 249,
				image: require("./img/Goods/14g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo15',
				article: '123496419',
				name: 'Шампунь для сухого і пошкодженого волосся зволожуючий без силіконів, 530 мл',
				description: 'La\'dor Moisture Balancing Shampoo Шампунь для сухого і пошкодженого волосся зволожуючий без силіконів, 530 мл - професійний засіб для догляду за волоссям та шкірою голови від люксовго корейського бренду не містить шкідливих силіконів, захищає локони та надає могутню антиоксидантну дію. Продукт підходить для частого використання і відмінно тонізує шкіру голови та промиває волосся, не пересушує їх. Рекомендуємо застосовувати шампунь в комплексі з іншими продуктами від La\'dor.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
				composition: 'Water, Sodium Laureth Sulfate, Sodium Lauryl Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Cocamide MEA, Glycol Distearate, Polyquaternium-10, Sodium Benzoate, Hydroxyacetophenone, Piroctone Olamine, Disodium EDTA, Citric Acid, PPG-3 Caprylyl Ether, Quaternium-80, Polyquaternium-7, Saponaria Officinalis Leaf Extract, Butylene Glycol, Acrylamidopropyltrimonium Chloride/Acrylamide Copolymer, Propylene Glycol, Lavandula Angustifolia (Lavender) Flower Extract, Monarda Didyma Leaf Extract, Mentha Piperita (Peppermint) Leaf Extract, Freesia Refracta Extract, Chamomilla Recutita (Matricaria) Flower Extract, Rosmarinus Officinalis (Rosemary) Leaf Extract, 1,2-Hexanediol, Ethylhexylglycerin, Fragrance, Alpha-Isomethyl Ionone, Citronellol, Hexyl Cinnamal',
				prise: 576,
				image: require("./img/Goods/15g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo16',
				article: '123496419',
				name: 'Шампунь для сухого і пошкодженого волосся безлужний, 900 мл',
				description: 'La\'dor Damage Protector Acid Shampoo Шампунь для сухого і пошкодженого волосся безлужний, 900 мл - особливий шампунь з pH 4,5, який делікатно очищає шкіру голови та волосся, не травмуючи їх, усуває лупу і запобігає її появі, бореться з сухістю, ламкістю й тьмяністю локонів. У чому переваги беслужного шампуню? Секрет полягає в тому, що наше волосся і шкіра голови люблять слабокислу середу якраз на рівні pH 4-4,5, а більшість доглядових засобів на ринку сильно перевищують цей рівень (pH 6-8), тим самим завдаючи шкоду локонам і шкірі. Тому шампунь від La\'dor не тільки ефективно очищає, але і відновлює кислотно-лужний баланс шкіри голови й перешкоджає вимиванню кортекса (матеріал, з яких складається волосся). У складі засобу також є масло аргана, яке насичується волосся, робить їх м\'якими та слухняними',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте піну великою кількістю теплої води. Процедуру можна повторити. Пам\'ятайте, що шампунь не потрібно наносити на всю довжину волосся, а тільки на корені',
				composition: 'Water, sodium Laureth Sulfate, Cocamidopropyl Betaine, Lauramide DEA, sodium Lauryl Sulfate, Argania spinosa Kernel oil, Disodium EDTA, Polyquaternium-10, Citric Acid, Climbazole, Sodium Benzoate, Phenoxyethanol, Cl 19140, fragrance',
				prise: 699,
				image: require("./img/Goods/16g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo17',
				article: '123496411',
				name: 'Шампунь для тонкого і пошкодженого волосся органічний безсульфатний, 150 мл',
				description: 'Lador Triplex Natural Shampoo Шампунь для тонкого і пошкодженого волосся органічний безсульфатний, 150 мл - органічний засіб для догляду за шкірою голови та волоссям, збагачений натуральними компонентами для дбайливого очищення й ефективного зволоження. Формула шампуню не містить шкідливі сульфати, парабени, силікони та при цьому посилено цілим комплексом корисних інгредієнтів: екстракт зеленого чаю, чорна смородина, екстракт червоного перцю, куркума, лимон, лаванда. Всі ці компоненти заспокоюють шкіру голови, усувають лупу, стимулюють ріст волосся і відновлюють здоров\'я локонів, робить їх м\'якими, шовковистим і блискучим. Шампунь має рівень pH-6.0 і підходить для чутливої шкіри голови.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте піну великою кількістю теплої води. Процедуру можна повторити. Пам\'ятайте, що шампунь не потрібно наносити на всю довжину волосся, а тільки на корені.',
				composition: 'Water, Lauryl Glucoside, Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, TEA-Cocoyl Glutamate, Polyquaternium-7, Guar Hydroxypropyltrimonium Chloride, Sodium Chloride, Lavandula Angustifolia (Lavender) Oil, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Camellia Sinesis Callus Culture Extract, Ribes Nigrum (Black Currant) Leaf Extract, Curcuma Longa (Turmeric) Root Extract, Citrus Limon (Lemon) Fruit Oil, Zanthoxylum Schinifolium Leaf Extract, Pulsatilla Koreana Extract, Citric Acid',
				prise: 275,
				image: require("./img/Goods/17g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Wonder18',
				article: '123496412',
				name: 'Міст для волосся для зміцнення і захисту, 100 мл',
				description: 'La\'dor Wonder Pic Clinic Water PH 4.9 Міст для волосся для зміцнення і захисту, 100 мл - міст у форматі спрею від  корейського бренду працює як незмивний кондиціонер і термозахист, насичує волосся корисними мікроелементами, зміцнює їх і захищає від впливу високих температур. Продукт має pH 4.9, близький нашій шкірі та волоссю, тому міст можна використовувати та для чутливої шкіри голови, і для пошкоджених локонів.',
				forWhat: 'відновлення',
				type: 'міст',
				application: 'міст використовується як 5-ий, останній етап догляду за волоссям. Його необхідно струсити перед використанням і наносити на вологе або сухе волосся з відстані 10-15 см. Не потребує змивання. Процедуру можна повторювати протягом дня.',
				composition: 'Hippophae Rhamnoides Fruit Extract, Cyclopentasiloxane, Hydroxypropyltrimonium Hydrolyzed Silk, Dimethicone, Polyquaternium-6, Polyquaternium-53, Dimethiconol, PEG-60 Hydrogenated Castor Oil, Trideceth-10, Caprylic/Capric Triglyceride, Steartrimonium Chloride, Caprylyl Glycol, Polysorbate 60, Lavandula Angustifolia (Lavender) Extract, Rosmarinus Officinalis (Rosemary) Extract, Thymus Vulgaris (Thyme) Extract, Mentha Arvensis Leaf Extract, Borago Officinalis Extract, Salvia Officinalis (Sage) Leaf Extract, Jasminum Officinale (Jasmine) Extract, Anthemis Nobilis Flower Extract, Disodium EDTA, Fragrance, Alpha-Isomethyl Ionone, Limonene, Butylphenyl Methylpropional',
				prise: 415,
				image: require("./img/Goods/18g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Fill19',
				article: '423496412',
				name: 'Філер для волосся відновлюючий, 150 мл',
				description: 'Lador Perfect Hair Fill-Up Філер для волосся живильний, 150 мл - унікальний засіб, який допоможе відновити пошкоджене, ламке волосся. Даний філер не складно використовувати в рутинному догляді, а результат від застосування не змусить себе чекати. Кераміди в складі формули створюють захисний бар\'єр на волоссі, який захищає їх від негативного впливу зовнішніх факторів. Колаген - унікальний компонент, який здатний насичувати та відновлювати пошкоджене волосся, доглядати за шкірою голови. Амінокислоти шовку активно зволожують кожен пошкоджений волосок зсередини, тим самим відновлюючи їх.',
				forWhat: 'зволоження і живлення',
				type: 'філер',
				application: 'змішати в не металевому посуді склад з водою в пропорції 1: 1, нанести на чисте, злегка вологе волосся. Розподілити по всій довжині, особливо на посічені кінчики. Через 20 хвилин змити теплою водою.',
				composition: 'Water, Steartrimonium Chloride, Alcohol, Hydrolyed Keratin, Hydrolyzed Collagen, Hydrolyzed Silk, Ceramide3ceramide NP, Sodium Benzoate, Hydroxyacetophenone, Fragrance.',
				prise: 480,
				image: require("./img/Goods/19g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo20',
				article: '523496412',
				name: 'Шампунь проти лупи, 530 мл',
				description: 'La\'dor Anti-Dandruff Shampoo Шампунь проти лупи, 530 мл - забезпечує ніжне і якісне очищення волосся, усуває лупу і причини її виникнення. В основі активної формули косметичного продукту екстракт лакриці, який вбиває шкідливі мікроби та бактерії, насичує шкіру голови вітамінним комплексом, регулює роботу сальних залоз і вироблення себума, запобігає надмірне випадання волосся. Екстракти камелії, дудника, портулаку, багатоквіткового горця, блетілли та смугастого  женьшеню відновлюють пошкоджені ділянки структури локонів, зміцнюють захисний шар, роблячи їх більш м\'якими, блискучими та слухняними. Гідролізований шовк попереджає ламкість, склеює посічені кінчики, захищає від сплутування. Екстракт ментолу покращує мікроциркуляцію крові, живить волосяні цибулини та відповідає за приємний освіжаючий запах засобу. Шампунь не порушує природний кислотно-лужний баланс.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'Нанести шампунь на вологе волосся і шкіру голови, помасажувати протягом 2-3 хвилин, потім змити теплою водою. При необхідності повторити процедуру.',
				composition: 'Water, Sodium C14-16 Olefin Sulfonate, Cocamidopropyl Betaine, Lauryl Glucoside, Glycerine, Lauramide DEA, PPG-3 Caprylyl Ether, Hydrolyzed Keratin, Hydrolyzed Wheat Protein, Panthenol, Butylene Glycol, Glycyrrhiza Glabra (Licorice) Root Extract, Polygonum Multiflorum Root Extract , Camellia Sinensis Leaf Extract, Angelica Gigas Root Extract, Panax Ginseng Root Extract, Portulaca Oleracea Extract, Rheum Palmatum Root Extract, Silkworm Extract, Bletilla Striata Root Extract, Carthamus Tinctorius (Safflower) Flower Extract, Hydroxyacetophenone, Climbazole, Salicylic Acid, Menthol, Citric acid, Dimethyl sulfone, Allantoin, Polyquaternium-10, betaine, Disodium EDTA, Fragrance',
				prise: 570,
				image: require("./img/Goods/20g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Fill21',
				article: '523496412',
				name: 'Набір філерів з кератином',
				description: 'Lador Perfect Hair Fill-Up Набір філерів з кератином - унікальний засіб, який допоможе відновити пошкоджене, ламке волосся. Даний філер не складно використовувати в рутинному догляді, а результат від застосування не змусить себе чекати. Кераміди в складі формули створюють захисний бар\'єр на волоссі, який захищає їх від негативного впливу зовнішніх факторів. Колаген - унікальний компонент, який здатний насичувати та відновлювати пошкоджене волосся, доглядати за шкірою голови. Амінокислоти шовку активно зволожують кожен пошкоджений волосок зсередини, тим самим відновлюючи їх.',
				forWhat: 'зволоження і живлення',
				type: 'філер',
				application: 'змішати в не металевому посуді склад з водою в пропорції 1: 1, нанести на чисте, злегка вологе волосся. Розподілити по всій довжині, особливо на посічені кінчики. Через 20 хвилин змити теплою водою',
				composition: 'Water, Steartrimonium Chloride, Alcohol, Hydrolyed Keratin, Hydrolyzed Collagen, Hydrolyzed Silk, Ceramide3ceramide NP, Sodium Benzoate, Hydroxyacetophenone, Fragrance.',
				prise: 879,
				image: require("./img/Goods/21g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Thermal22',
				article: '523492412',
				name: 'Термозахисний спрей для укладки волосся, 100 мл',
				description: 'Lador Thermal Protection Термозахисний спрей для укладки волосся, 100 мл - пом\'якшувальний засіб для відновлення і блиску волосся. Живить і насичує локони від коренів до кінчиків, робить волосся еластичним, пружним, здоровим на вигляд. Використовувати в якості термозахисту при використанні плойки, фена, прасування. Засіб створює легку захисну плівку на волоссі, яка і захищає від теплого впливу гарячих приладів, і від негативних факторів зовнішнього середовища.',
				forWhat: 'термозахист',
				type: 'захист',
				application: 'потрусити балончик перед використанням. Розпилити на волосся на відстані 10-15 см.',
				composition: 'Water, Butylene Glycol, Polyglyceryl-10 Laurate, Hydrolyzed Collagen, Polyglyceryl-4 Laurate, Polyglycerin-3, Benzyl Glycol, Caprylyl/Capryl Glucoside, Silicone Quaternium-22, Quaternium-81, Arginine, PCA, Cetrimonium Chloride, Polyglyceryl-3 Caprate, Dipropylene Glycol, Propylene Glycol, Viola Mandshurica Flower Extract, Gardenia Florida Fruit Extract, Raspberry Ketone, Benzophenone-5, Hydrolyzed Soy Protein, Hydrolyzed Wheat Protein, Hydrolyzed Corn Protein, Aphanothece Sacrum Polysaccharides, Glycine, Serine, Glutamic Acid, Aspartic Acid, Leucine, Alanine, Lysine, Tyrosine, Phenylalanine, Threonine, Proline, Valine, Isoleucine, Histidine, Methionine, Cysteine, Ethylhexylglycerin, 1,2-Hexanediol, Disodium EDTA, Fragrance, Hexyl Cinnamal',
				prise: 515,
				image: require("./img/Goods/22g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo23',
				article: '223492412',
				name: 'Шампунь для волосся зволожуючий, 600 мл',
				description: 'Lador Wonder Bubble Shampoo Шампунь для волосся зволожуючий, 600 мл - відмінний засіб для глибокого очищення шкіри голови та збереження вологи. Активний компонент складу - кератин, завдання якого розгладити відкриті лусочки волосся, зробити їх гладенькими на вигляд. Волосся після шампуню, дуже м\'які, слухняні, нагодовані вологою. Підійде для ніжної шкіри голови, особливо вибагливого волосся. Великий об’єм зручний для тривалого використання.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанести засіб на корені волосся, легкими, масажними рухами розтерти по шкірі голови, змити теплою водою',
				composition: 'Water, Sodium Laureth Sulfate, Ammonium Lauryl Sulfate, Cocamidopropyl Betaine, Disodium Cocoamphodiactate, Dimethicone, Glycol Distearate. Cocamide Mea, Polyquaternium07, Dipropylene Glucol, Polyquaternium-10, Guar Hydroxypropyltrimonium Chloride, Hydroxyethyl Urea. Sodium Hyaluronate, Hydrolyzed Keratin, Lawsonia Inermis Extract, Pisim Sativum Yl Hexapeptide-8, Copper Tripeptide-1, Palmitoyl Pentapeptide-4, Tripeptide-1, Hexapeptide-9, Polyglyceryl-10 Laurate, Citric Acid, C12-15 Pareth-3, Aphanothece Sacrum Polysaccharides, Hydroxyacetophenone, Fragrance.',
				prise: 749,
				image: require("./img/Goods/23g.jpg"),
				alt: 'is top image',
			},
			{
				id: 'Shampoo24',
				article: '223492112',
				name: 'Безсульфатний шампунь з кератином, 150 мл',
				description: 'La\'dor Keratin LPP Shampoo Шампунь для волосся з кератином безсульфатний, 150 мл - унікальний засіб для салонного догляду за волоссям. Безсульфатний шампунь працює в двох напрямках - дбайливо очищає волосся без участі шкідливих речовин і при цьому насичує локони кератином, відновлюючи їх структуру. Як відомо, кератин - це будівельний матеріал для локонів і при його втраті вони стають ламкими, сухими і тьмяним. Шампунь з кератином заповнює «порожнечі» у волоссі і тим самим реконструює їх. Крім того, відсутність шкідливих сульфатів, парабенів і силіконів в складі продукту сприятливо впливає на здоров\'я локонів. Так, безсульфатний шампунь не піниться так, як звичайний, але не варто цього боятися. Засіб ефективно очищає шкіру голови і волосся, не травмуючи їх. Ще одна перевага кератинового шампуню від La\'dor - він збагачений натуральними амінокислотами, протеїнами шовку та розкішним коктейлем їз різних масел (лаванди, камелії, жожоба, авокадо, Аргана, евкаліпта). Весь цей комплекс корисних речовин робить шампунь не тільки засобом для очищення, а й одним з етапів ефективного лікування волосся.',
				forWhat: 'очищення',
				type: 'шампунь',
				application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови і коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
				composition: 'Cocoamidopropyl Betaine, Disodium Laureth Sulfosuccinate, lauramine oxide, Glycerine, Butylene Glycol, TEA-Cocoyl Glutamate, Cocamide DEA, PEG-120 Methyl Glucose Dioleate, PPG-3 Caprylyl Ether, PEG-7 Glyceryl Cocoate, Betaine, Hydroxypropyl Chitosan , Trehalose, Hydrolyzed Wheat Protein, Hydrolized Corn Protein, Hydrolized Soy Protein, Hydrolyzed Silk, Sodium Hyaluronate, Dipropylene Glycol, Zein, Argania Spinosa Kernel Oil, Avocado Oil, Camellia Japonica Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Citric Acid, Polyquaternium-10, Hydroxyacetophenone, Sodium Benzoate, Fragrance.',
				prise: 249,
				image: require("./img/Goods/24g.jpg"),
				alt: 'is top image',
			},
		],
		dataMasters: [
			{
				id: 'hairdresser',
				title: 'Перукар',
				name: 'Анна',
				avatar: require("./img/Masters/CI1.png"),
				alt: 'avatars of the masters',
				image1: require("./img/Masters/MP1.jpg"),
				image2: require("./img/Masters/MP2.jpg"),
				image3: require("./img/Masters/MP3.jpg"),
				image4: require("./img/Masters/MP4.jpg"),
				image5: require("./img/Masters/MP5.jpg"),
				image6: require("./img/Masters/MP6.jpg"),
				subTitle1: 'Стрижка',
				subTitle2: 'Фарбування',
				subTitle3: 'Укладання та зачіска',
				subTitle4: 'Лікування волосся',
				subTitle5: 'Доглядові процедури',
				subTitle6: 'Нарощування волосся',
				text1: 'Стрижка - це не просто необхідна процедура для основного догляду за волоссям, а спосіб висловити себе, відправна точка іміджу і стилю. Правильно підібрана та виконана стрижка здатна підкреслити переваги та приховати недоліки, зробити обличчя молодшим або, навпаки, додати кілька років. Професійний перукар враховує багато параметрів, таких як форма, будова обличчя, характер та спосіб життя клієнта.',
				text2: 'Фарбування - друга за популярністю послуга, яка теж постійно еволюціонує та вдосконалюється. Розглянемо найпопулярніші види фарбування на сьогоднішній день: класичне перманентне фарбування, тонування волосся, мелірування, колорування, брондування, омбре, Air Touch, декапірування.',
				text3: 'Укладання волосся завжди залишається популярною перукарською послугою через свою універсальність. Під укладанням маються на увазі різні операції, які дозволяють надати волоссю потрібну форму і об\'єм. Зачіска — це, власне, складніша форма укладання. Вони також бувають різними за формою та призначенням.',
				text4: 'Витонченість і ламкість, ослаблене або пересушене волосся, лупа, перетин кінців, випадання волосся, швидке забруднення шкіри голови – ці та інші проблеми можна вирішити за допомогою сучасних процедур. Розглянемо найпопулярніші салонні методи лікування: ампульне лікування, озонотерапія, мезотерапія, стрижка гарячими ножицями.',
				text5: 'Послуги з догляду за волоссям посідають особливе місце у класифікації перукарських послуг. Вони надають загальний оздоровлюючий ефект для шкіри голови, покращують стан волосся, додають яскравості, зволоженості та блиску: масаж голови, ламінування волосся, кератинове випрямлення волосся, елюмінування.',
				text6: 'Перукарня послуга з нарощування волосся дозволяє швидко змінити свій образ, тому вже багато років залишається однією з найпопулярніших на ринку. Залежно від особливостей та стану волосся, майстер вибирає одну з методик, які діляться на «гарячі» та «холодні» (з використанням високих температур або без нього): капсульне нарощування, стрічкове нарощування, ультразвукове нарощування.',
				altImage: 'examples of work',
			},
			{
				id: 'manicure',
				title: 'Манікюр',
				name: 'Елена',
				avatar: require("./img/Masters/CI2.png"),
				alt: 'avatars of the masters',
				image1: require("./img/Masters/MM1.jpg"),
				image2: require("./img/Masters/MM2.jpg"),
				image3: require("./img/Masters/MM3.jpg"),
				image4: require("./img/Masters/MM4.jpg"),
				image5: require("./img/Masters/MM5.jpg"),
				image6: require("./img/Masters/MM6.jpg"),
				subTitle1: 'Гігієнічний манікюр',
				subTitle2: 'Бразильський манікюр',
				subTitle3: 'Гарячий манікюр',
				subTitle4: 'Манікюр з аури',
				subTitle5: 'Японський манікюр',
				subTitle6: 'Смарт манікюр',
				text1: 'Мета гігієнічного манікюру - надання нігтям красивої форми, видалення задирок, кутикули і ділянок бічних шкірних валиків, що ороговіли. Його рекомендується робити жінкам, чоловікам та дітям щотижня.',
				text2: 'Бразильський манікюр - нова, але дуже популярна послуга в nail-індустрії. Крім обробки нігтів, процедура включає догляд за кутикулою та шкірою рук. Усі маніпуляції виконують за допомогою стерильного одноразового набору, без використання різальних та гострих інструментів.',
				text3: 'Гарячий манікюр - процедура догляду за руками за допомогою ванни з особливим розчином. Це процес відпарювання нігтів за допомогою підігрітої води і лосьйонів або трав. Зараз існують навіть спеціальні ванни, які підтримуватимуть потрібну для процедури температуру, що, погодься, дуже зручно.',
				text4: 'Манікюр аура, або aura nails, став популярним на початку літа, тому що ефектно виглядає, до того ж наповнений змістом. У малюнку на нігтях майстер може повторити колір вашої аури, найпростіший спосіб побачити її - завантажити спеціальний мобільний додаток (наприклад, Online Aura Photography або Aura Camera).',
				text5: 'Японський манікюр – техніка догляду за нігтями, популярна у всьому світі. У манікюрних та педикюрних салонах цю процедуру ще називають перманентним глянсуванням нігтів, запечатуванням нігтьової пластини або біоманікюром.',
				text6: 'Ця система поєднується з усіма кольоровими гелями. SMART-манікюр надає нігтям здорового, природного вигляду. Навіть при відростанні їх зовнішній вигляд залишається привабливим, оскільки відсутня яскраво-виражена межа між нігтьовою пластиною, що відросла, і SMART-покриттям. Такий манікюр можна багаторазово покривати лаком.',
				altImage: 'examples of work',
			},
			{
				id: 'pedicure',
				title: 'Педикюр',
				name: 'Розанна',
				avatar: require("./img/Masters/CI3.png"),
				alt: 'avatars of the masters',
				image1: require("./img/Masters/MPP1.jpg"),
				image2: require("./img/Masters/MPP2.jpg"),
				image3: require("./img/Masters/MPP3.jpg"),
				image4: require("./img/Masters/MPP4.jpg"),
				image5: require("./img/Masters/MPP5.jpg"),
				image6: require("./img/Masters/MPP6.jpg"),
				subTitle1: 'Класичний педикюр',
				subTitle2: 'Апаратний педикюр',
				subTitle3: 'Комбінований педикюр',
				subTitle4: 'СПА-педикюр',
				subTitle5: 'Європейський педикюр',
				subTitle6: 'Сухий педикюр',
				text1: 'Класичний педикюр поділяється на два види: обрізний та європейський – відрізняються вони способом обробки кутикули. При класичному обрізному педикюрі стопи потрібно розпарити у ванні для ніг, після чого кутикула дерев\'яною паличкою легко зрушується до нігтьової лунки і зрізається ножицями манікюрними або щипчиками. При необрізному педикюрі видаляють кутикулу за допомогою спеціального засобу для видалення кутикули.',
				text2: 'В основі цього педикюру лежить той самий принцип, що й у його класичному виконанні, але в цій процедурі використовують лише розм\'якшувальні засоби, а не розпарюють стопи водою, як у педикюрі обрізів. Для обробки шкіри та нігтів використовують апарат, що дозволяє відшліфувати огрубілі ділянки шкіри навіть у важкодоступних місцях.',
				text3: 'Це гібрид апаратного і класичного педикюру, він поєднує в собі переваги двох основних видів, що дозволяє досягти кращих результатів, як правило, обробка шкіри стоп здійснюється апаратом, а нігтів вручну.',
				text4: 'Останнім часом все більшої популярності набуває СПА-педикюр. Ця процедура зазвичай робиться тільки після класичного або апаратного педикюру і включає не тільки обробку стоп з метою надання їм красивого вигляду, але і спеціальний догляд за ними і релаксацію. При виконанні цієї процедури використовується косметика, в яку входять корисні компоненти: екстракти рослин, бруду, ефірні олії, водорості, солі, термальні води та інші натуральні інгредієнти. На першому етапі робиться ванна для ніг з додаванням екстрактів масел, після чого пілінг з натуральним скрабом, різні маски і на завершення процедури масаж.',
				text5: 'Ключова відмінність європейського та класичного манікюрів полягає у відмові від розм\'якшення шкіри водою та від використання ріжучих інструментів. Шкіра розм\'якшується спеціальними засобами для видалення кутикули та натоптишів, після чого видаляється паличкою або скребком. А після обробки шкіри можна відразу приступати до нанесення лаку.',
				text6: 'Цей вид педикюру схожий на європейський. При цьому особлива увага приділяється обробці шкіри на суху. Тобто всі натоптиші, тріщини, кутикули спилюються ще до розм\'якшення спеціальними засобами. В рамках цієї техніки, як правило, використовуються керамічні або лазерні пилки нового покоління, які дозволяють спилювати тільки сухі ділянки, не пошкоджуючи саму шкіру. Далі виконуються розм\'якшення та остаточне видалення кутикули та птеригія ремувером.',
				altImage: 'examples of work',
			},
			{
				id: 'cosmetologist',
				title: 'Косметолог',
				name: 'Вера',
				avatar: require("./img/Masters/CI4.png"),
				alt: 'avatars of the masters',
				image1: require("./img/Masters/MK1.jpg"),
				image2: require("./img/Masters/MK2.jpg"),
				image3: require("./img/Masters/MK3.jpg"),
				image4: require("./img/Masters/MK4.jpg"),
				image5: require("./img/Masters/MK5.jpg"),
				image6: require("./img/Masters/MK6.jpg"),
				subTitle1: 'Догляд за шкірою обличчя',
				subTitle2: 'Косметологія тіла',
				subTitle3: 'Апаратна косметологія',
				subTitle4: 'Післяопераційна реабілітація',
				subTitle5: 'Пересадка волосся',
				subTitle6: 'Процедури',
				text1: 'Прагнення дбати про свою зовнішність властиво кожній людині. З кожним роком косметологічний догляд за шкірою обличчя стає все більш популярним серед чоловіків. Салон підтримує цю тенденцію, пропонуючи саме ті косметологічні процедури, ін\'єкційні та апаратні процедури, які підходять жіночій та чоловічій шкірі.',
				text2: 'Ідеальне тіло — мрія практично кожної жінки. Однак для перемоги над целюлітом та жировими відкладеннями далеко не завжди достатньо дієти та завзятих занять у тренажерному залі. Позбутися зайвого жиру і зробити фігуру стрункішою допоможуть ефективні безопераційні методи — ін\'єкції ліполітиків та апаратна косметологія.',
				text3: 'Сучасні апарати дозволяють удосконалити будь-яку частину вашого тіла. І роблять це самостійно, або в комбінації з традиційними методами.',
				text4: 'Робота фахівців не припиняється за дверима операційною, а продовжується до повної реабілітації клієнта. Ми створили унікальні методики реабілітаційних процедур. Вони допоможуть скоротити період реабілітації на кілька місяців.',
				text5: 'Більшість жінок і чоловіків з віком помічають, що їх волосся значно порідшало. Якщо раніше людям, які страждають на облисіння, доводилося користуватися народними методами або змиритися, то сьогодні є швидке та ефективне вирішення цієї проблеми – пересадка волосся.',
				text6: 'Надаємо повний спектр малоінвазивних процедур та ефективних апаратних протоколів, а також грамотно підібраний професійний домашній догляд. А ще це комплекс кастомізованих детокс-програм, масажів та превентивних методик, за допомогою яких ви підкреслите свою природну красу, збережете молодість та покращите загальний стан здоров\'я.',
				altImage: 'examples of work',
			},
			{
				id: 'masagist',
				title: 'Масажист',
				name: 'Леся',
				avatar: require("./img/Masters/CI5.png"),
				alt: 'avatars of the masters',
				image1: require("./img/Masters/MF1.jpg"),
				image2: require("./img/Masters/MF2.jpg"),
				image3: require("./img/Masters/MF3.jpg"),
				image4: require("./img/Masters/MF4.jpg"),
				image5: require("./img/Masters/MF5.jpg"),
				image6: require("./img/Masters/MF6.jpg"),
				subTitle1: 'Загальний масаж',
				subTitle2: 'Лікувальний масаж спини',
				subTitle3: 'Дитячий масаж',
				subTitle4: 'Масаж шийно-комірцевої зони',
				subTitle5: 'Спортивний масаж.',
				subTitle6: 'Антицелюлітний масаж',
				text1: 'Оздоровчий, знімає втому та відновлює працездатність, попереджає перевтому та створює гарний настрій. Тривалість процедури – 1 год. Основні прийоми при загальному масажі, такі ж, як і при класичному масажі: погладжування, розтирання, розминання, вібрація. Техніка загального масажу, еклектична від природи, замислювалася прихильниками філософії холізму як поєднання східних прийомів та сучасних принципів анатомії та фізіології.',
				text2: 'Знімає напругу та біль у спині, нормалізує обмінні процеси. Тривалість – 30 хвилин. Малорухливий спосіб життя або, навпаки, надмірні фізичні навантаження, неправильне харчування та багато інших факторів можуть призвести до появи болів у спині. Лікувальний масаж спини ефективний при лікуванні хребта та зняття напруги з м\'язової системи. Ефективність лікувального масажу спини доведена при остеохондрозі, грижі хребта, синдромі хронічної втоми та інших захворюваннях, характерних для чинного мешканця сучасного міста.',
				text3: 'Найбезпечніший і найакуратніший з усіх видів масажу. Дитячий масаж може проводитися не тільки з профілактичною та гігієнічною метою, але й у випадках, коли є якісь відхилення у стані здоров\'я або фізичному розвитку. Найчастіше дитячий масаж роблять при порушенні нормальної функції хребта, слабкість м\'язів і зв\'язкового апарату, що різко проявляється, деякі порушення в роботі шлунково-кишкового тракту, перенесені захворювання.',
				text4: 'Шийно-комірникова зона частіше за інші зони тіла людини піддається впливу негативних факторів середовища. Саме в шийно-комірцевій зоні найчастіше спостерігається виникнення застійних явищ, набряклості, затискання хребців, відкладення солей та порушення в роботі сполучної тканини. В результаті виникають такі захворювання, як остеохондроз, сколіоз, кривошия, утворюються лопаткові спайки. Крім того, виникають болі в спині, шиї, плечах, голові.',
				text5: 'Цілі спортивного масажу - загальне поліпшення стану спортсмена, підвищення його фізичних можливостей, зняття втоми після навантажень, мінімізація ймовірності спортивних травм або відновлення після них. Загалом цей спосіб впливу можна розділити на кілька підгруп: тренувальний, попередній, відновлювальний. Спортивний масаж – невід\'ємна частина відновлювального періоду після спортивних травм. Найбільш поширені з них – забиття, вивихи, розтягнення зв\'язок, переломи, пошкодження м\'язів та сухожилля.',
				text6: 'Целюліт – це локальне порушення метаболізму, що відбувається у жировій тканині. Ефективність методу полягає у тривалому інтенсивному впливі на проблемні зони організму до руйнування жирових відкладень. Посилення кровообігу в жировій тканині та збільшення кількості гормонів у крові стимулюватиме звільнення жиру з клітини. Шкіра, що масажується, стає гладкою, пружною, еластичною. Як наслідок – загальне оздоровлення організму.',
				altImage: 'examples of work',
			},
			{
				id: 'designer',
				title: 'Візаж',
				name: 'Тетяна',
				avatar: require("./img/Masters/CI6.png"),
				alt: 'avatars of the masters',
				image1: require("./img/Masters/MV1.jpg"),
				image2: require("./img/Masters/MV2.jpg"),
				image3: require("./img/Masters/MV3.jpg"),
				image4: require("./img/Masters/MV4.jpg"),
				image5: require("./img/Masters/MV5.jpg"),
				image6: require("./img/Masters/MV6.jpg"),
				subTitle1: 'Вечірній макіяж',
				subTitle2: 'Весільний макіяж',
				subTitle3: 'Ліфтінг-макіяж',
				subTitle4: 'Макіяж зони декольте',
				subTitle5: 'Карнавальний макіяж',
				subTitle6: 'Smoky eyes» або димчастий макіяж',
				text1: 'Вечірній макіяж призначений для урочистих прийомів, вечірок з друзями та інших вечірніх заходів. Він істотно відрізняється від денного макіяжу. Для ефектного образу слід враховувати особливості і тип особи. ',
				text2: 'Весільний макіяж - це щось середнє між вечірнім і денним варіантом макіяжу. Він повинен бути ніжним, але при цьому бути досить виразним, для того, щоб очі нареченої на весільних фотографіях виглядали більш виразно.',
				text3: 'Ліфтинг означає "підтяжка", тобто коригування овалу обличчя за допомогою макіяжу. Не секрет, що з віком він трохи пливе, і щоб це виправити і потрібні спеціальні мейк-ап-прийоми, а також косметичні засоби для контурингу, такі як тональний крем, хайлайтер, бронзер і рум\'яна.',
				text4: 'Шкіра декольте і шиї тонка, в ній мало підшкірно-жирової клітковини. Тому для догляду за цими областями потрібна делікатна косметика. Якщо не приділяти належної уваги шиї та декольте, ці зони швидко в\'янутимуть і видаватимуть справжній вік.',
				text5: 'Карнавальний макіяж - сліпуче яскравий і багатобарвний візерунок на обличчі, який можна створити виключно за допомогою професійних косметичних засобів.',
				text6: 'Димчастий макіяж - це техніка розтушовки, а не чіткі вказівки щодо того, який напрямок задати тіням, так що знайти вдалий тип розтушовки для своєї форми очей зможе кожна. Тут все працює так само, як і зі стрілками - smoky eyes підходить будь-якій формі очей.',
				altImage: 'examples of work',
			},
		],
		dataWWD: [
			{
				id: 'hair',
				title: 'Перукарські послуги',
				description: 'Ми надаємо послуги популяції по догляду за волоссям (різання, упряжування, створення волосся, фарбування, танення та іншого фарбування, стрижки, гоління та стрижки, стрижка та стрижка бороди та вус тощо) в номері обладнаному спеціально для цього.',
				subtitle1: 'Тонування сивини',
				subtitlePrice1: '2945',
				subSubTitle1: 'Якщо раніше вам доводилося миритися із сивиною або повністю тонувати все волосся, то сьогодні цього можна уникнути. Сучасні техніки фарбування волосся дають змогу домогтися природних переходів, що імітують натуральні відтінки. Наш салон пропонує приховане чоловіче фарбування і камуфлювання сивини.',
				subtitle2: 'Ламінування волосся',
				subtitlePrice2: '5345',
				subSubTitle2: 'Моментально зробити тьмяне, посічене і слабке волосся блискучим, сильним і гладким - це реальність, що стала можливою завдяки ламінуванню. Ця техніка творить справжнє диво! Вона дає змогу реанімувати і покращити зовнішній вигляд волосся всього за одну процедуру. Зробити ламінування волосся в Києві за світовими стандартами можна в салонах краси Kika-Style. Ми гарантуємо результат і його довговічність.',
				subtitle3: 'Корекція кольору волосся',
				subtitlePrice3: '2345',
				subSubTitle3: 'Все, що красиво в житті вимагає турботи і уваги, а з точки зору догляду і догляду, це завдання може бути довірено нам. Мережа салонів краси в Києві допоможе зберегти здоров\'я волосся завдяки кваліфікованим майстрам, які будуть раді надати вам догляд, стрижку, чистий колiр.',
				subtitle4: 'Стрижка волосся',
				subtitlePrice4: '1345',
				subSubTitle4: 'Техніка стрижки не існує як така. Вона має на меті - досягнення результату. Ми не хочемо викликати негативних емоцій у гостей салону. Дискутуємо з приводу бажаної форми, питаємо думку, вивчаємо звички та стиль. Наприклад, дівчина вперше приходить до майстра. Стиліст звертає увагу, в чому одягнена гостя, як лежить її волосся в момент, коли вона тільки прийшла. У розмові майстер дізнається більше, аналізує отриману інформацію, оцінює стан, структуру, колір волосся. Можливо, звичайний стиль гості відрізняється. Зараз вона має довіритися майстру, а майстер хоче виправдати очікування.',
				image: require("./img/WWD/ab1.png"),
				image1: require("./img/WWD/ab11.jpg"),
				image2: require("./img/WWD/ab12.jpg"),
				image3: require("./img/WWD/ab13.jpg"),
				image4: require("./img/WWD/ab14.jpg"),
				alt: 'is top image',
			},
			{
				id: 'manicure',
				title: 'Манікюр',
				description: 'Турбота про красу і здоров’я нігтів – одна з найважливіших складових догляду за собою для всіх сучасних жінок і чоловіків, адже доглянуті нігтики на руках і ногах – незамінна деталь образу. Зовнішній вигляд рук говорить не тільки про вік людини, про його соціальний статус, а й про те, наскільки ретельно він за собою стежить і наскільки він охайний. Погодьтеся, нікому не сподобаються брудні нігті і суха, потріскана шкіра рук. Безумовно, без акуратного манікюру руки не можуть виглядати привабливо. Облуплений лак або недоглянуті нігті здатні зіпсувати будь-який самий продуманий образ.',
				subtitle1: 'Манікюр класичний',
				subtitlePrice1: '345',
				subSubTitle1: 'Класичний манікюр або, як його називають, вважається одним з найпопулярніших видів манікюру в Києві і Україні. У процесі кутикули і суміжних бічних роликів видаляються з росту за допомогою різання інструментів - ножиці або шматок для кутикули.',
				subtitle2: 'Манікюр апаратний',
				subtitlePrice2: '245',
				subSubTitle2: 'Манікюр апаратного забезпечення - це техніка манікюру, в якій майстер обробляє кутикулу і нігтьову пластину з фрезерним верстатом і сопла. Машина може завершити всі етапи, від видалення старого покриття до шліфування кутикули.',
				subtitle3: 'Манікюр європейський',
				subtitlePrice3: '395',
				subSubTitle3: 'Європейський манікюр відрізняється від класики тим, що кутикула не вирізана. Його видаляють, як і будь-який манікюр, але у випадку з європейським манікюром, не з ножицями. Хоча сенс манікюру як такого залишився, тобто догляд за нігтями і руками, європейський манікюр вважається більш ніжним методом.',
				subtitle4: 'Манікюр SPA',
				subtitlePrice4: '259',
				subSubTitle4: 'SPA - це водоочищення для здоров\'я організму, що проводиться в комплексі. SPA педикюр - це догляд за оздоровленням для ноги, пальців, нігтів, де активно використовуються лазні, трави і масло.',
				image: require("./img/WWD/ab2.png"),
				image1: require("./img/WWD/ab21.jpg"),
				image2: require("./img/WWD/ab22.jpg"),
				image3: require("./img/WWD/ab23.jpg"),
				image4: require("./img/WWD/ab24.jpg"),
				alt: 'is top image',
			},
			{
				id: 'pedicure',
				title: 'Педикюр',
				description: 'Спеціальний догляд за ногами (наприклад, видалення кутикул, полірування нігтів) або покриття нігтів лаком. По суті це аналог манікюру ніг. Чоловічий ты жiночий педикюр – процедури, що забезпечують акуратність і охайність представникiв рiзноi статі.',
				subtitle1: 'Педикюр класичний',
				subtitlePrice1: '345',
				subSubTitle1: 'Класичний педикюр - це процедура, яка використовує залізо інструменти для обрізання надлишкової шкіри навколо нігтів, а товста, суха шкіра на нозі видаляється спеціальними пілісами.',
				subtitle2: 'Педикюр комбінований',
				subtitlePrice2: '745',
				subSubTitle2: 'Комбінований педикюр - це набір апаратних і ручних методів обробки шкіри нігтів і нігтьових пластин. У цій формі педикюр обробляється вручну, а стопа і пальці обробляються за допомогою обертових насадок спеціальної машини.',
				subtitle3: 'Видалення мозолів',
				subtitlePrice3: '935',
				subSubTitle3: 'Видалення мозолів скальпелем — це класичний метод видалення великих сухих мозолів та глибоких стрижневих мозолів на стопах і пальцях ніг. Процедура проводиться під місцевим наркозом та займає до 1 години. Реабілітаційний період триває 7-10 днів, а для досягнення результату, як правило, достатньо одного сеансу.',
				subtitle4: 'Педикюр SPA',
				subtitlePrice4: '165',
				subSubTitle4: 'SPA - це водоочищення для здоров\'я організму, що проводиться в комплексі. SPA педикюр - це догляд за оздоровленням для ноги, пальців, нігтів, де активно використовуються лазні, трави і масло.',
				image: require("./img/WWD/ab3.png"),
				image1: require("./img/WWD/ab31.jpg"),
				image2: require("./img/WWD/ab32.jpg"),
				image3: require("./img/WWD/ab33.jpg"),
				image4: require("./img/WWD/ab34.jpg"),
				alt: 'is top image',
			},
			{
				id: 'cosmetology',
				title: 'Косметологія',
				description: 'Ін\'єкційна косметологія - це метод корекції віку або деформації змін в обличчі і організмі через ін\'єкції, які стимулюють кровоток, активується синтез колагену і еластину, а також посилюються захисні властивості шкіри.',
				subtitle1: 'Мезотерапія обличчя',
				subtitlePrice1: '2345',
				subSubTitle1: 'Мезотерапія обличчя – малоінвазивна процедура, при якій комплекс корисних мінералів і амінокислот доставляється в мезодерму шляхом ін’єкцій. Ціна вказана від ... і може збільшитися в залежності від того, який препарат ви вибираєте і скільки процедур ви хочете зробити. ',
				subtitle2: 'Біоревіталізація',
				subtitlePrice2: '3345',
				subSubTitle2: 'Біоревіталізація – процедура ін’єкційного або безін’єкційного введення гіалуронової кислоти під шкіру.  Ціна вказана від ... і може збільшитися в залежності від того, який препарат ви вибираєте і скільки процедур ви хочете зробити. ',
				subtitle3: 'Ін’єкції ботулотоксину',
				subtitlePrice3: '1500',
				subSubTitle3: 'Ін’єкції ботокса – найбільш ефективна і затребувана косметологічна процедура омолодження шкіри обличчя і боротьби з мімічними зморшками.  Ціна вказана від ... і може збільшитися в залежності від того, який препарат ви вибираєте і скільки процедур ви хочете зробити. ',
				subtitle4: 'Мезотерапія волосся',
				subtitlePrice4: '1345',
				subSubTitle4: 'Скажи стоп надмірному випадінню, ламкості волосся і посіченим кінчикам!  Ціна вказана від ... і може збільшитися в залежності від того, який препарат ви вибираєте і скільки процедур ви хочете зробити. ',
				image: require("./img/WWD/ab4.png"),
				image1: require("./img/WWD/ab41.jpg"),
				image2: require("./img/WWD/ab42.jpg"),
				image3: require("./img/WWD/ab43.jpg"),
				image4: require("./img/WWD/ab44.jpg"),
				alt: 'is top image',
			},
			{
				id: 'massage',
				title: 'Естет із тіла',
				description: 'Масаж - одна з ручних методик,[2] набір механічних і рефлекторних впливів на тканини і органи, у вигляді тертя, тиску, вібрації здійснюється безпосередньо на поверхні людського тіла, як руками, так і з спеціальними апаратами через повітря, водні або інші середовища, з метою досягнення терапевтичного або іншого ефекту.',
				subtitle1: 'Стоун масаж (60 хв)',
				subtitlePrice1: '1100',
				subSubTitle1: 'Стоун-масаж – древня східна техніка, якої кілька тисяч років.',
				subtitle2: 'Класичний масаж',
				subtitlePrice2: '645',
				subSubTitle2: 'Класичний масаж – один з найсучасніших методів лікування та профілактики багатьох захворювань.',
				subtitle3: 'Лікувальний масаж',
				subtitlePrice3: '700',
				subSubTitle3: 'Лікувальний масаж – це одна з найбільш ефективних оздоровчих процедур, що полягає в мануальному впливі на різні ділянки тіла.',
				subtitle4: 'Антицелюлітний масаж',
				subtitlePrice4: '945',
				subSubTitle4: 'Антицелюлітний масаж допомагає зменшити відкладення жиру і вирівняти поверхню шкіри.',
				image: require("./img/WWD/ab5.png"),
				image1: require("./img/WWD/ab51.jpg"),
				image2: require("./img/WWD/ab52.jpg"),
				image3: require("./img/WWD/ab53.jpg"),
				image4: require("./img/WWD/ab54.jpg"),
				alt: 'is top image',
			},
			{
				id: 'spa',
				title: 'SPA послуги',
				description: 'SPA - це набір розслабляючих процедур, спрямованих на омолодження і реабілітацію людського тіла: тілесні і духовні. Водорості, спеціальний бруд лікування, використовуються водоочищення.',
				subtitle1: 'Віскі-сповивання',
				subtitlePrice1: '845',
				subSubTitle1: 'Whiskey-shrinking - це процедура пов\'язування, заснована на австрійській косметиці бренду Aromaderm Styx Naturcosmetics. Інтригуюча процедура, яка допомагає в боротьбі із зайвою вагою.',
				subtitle2: 'Пілінг тіла',
				subtitlePrice2: '545',
				subSubTitle2: 'Пілінг тіла – ефективна і дуже приємна процедура, що дозволяє відновити і оздоровити поверхню шкіри.',
				subtitle3: 'Обгортання “Шоколадна акварель”',
				subtitlePrice3: '760',
				subSubTitle3: 'Шоколадне обгортання вважається кращим і, мабуть, найприємнішим способом позбавиться від целюліту, надати шкірі ніжність і бархатистість, а також омолодити її.',
				subtitle4: 'Антицелюлітне обгортання',
				subtitlePrice4: '695',
				subSubTitle4: 'Антицелюлітне обгортання – одна з найбільш затребуваних процедур корекції фігури і боротьби з ефектом «апельсинової кірки».',
				image: require("./img/WWD/ab6.png"),
				image1: require("./img/WWD/ab61.jpg"),
				image2: require("./img/WWD/ab62.jpg"),
				image3: require("./img/WWD/ab63.jpg"),
				image4: require("./img/WWD/ab64.jpg"),
				alt: 'is top image',
			},
		],
		dataComment: [{
			id:1,
			message:'гребаный тест',
			likesCount: 1,
		}],
		newCommentText: 'test222',
	},
	_callSubscriber() {
		console.log('data changed');
	},
	
	getData() {
		return this._data;
	},
	subscribe(observer) {
		this._callSubscriber = observer;
	},
	
	dispatch(action) {
		if (action.type === ADD_COMMENT) {
			let newComment = {
				id: 5,
				message: this._data.newCommentText,
				likesCount: 0,
			};
			this._data.dataComment.push(newComment);
			this._data.newCommentText = '';
			this._callSubscriber(this._data);
		} else if (action.type === UPDATE_NEW_COMMENT_TEXT) {
			this._data.newCommentText = action.newCommentMessage;
			this._callSubscriber(this._data);
			
		}
	}
}

export const addCommentActionCreator = () => ({type: ADD_COMMENT});
export const updateNewCommentTextActionCreator = (text) => ({
	type: UPDATE_NEW_COMMENT_TEXT,
	newCommentMessage: text
})


export default store;
window.store = store;