const resources = {
	ua: {
		translation: {
			Technical: {
				currency: 'грн',
			},
			NavBurger: {
				navLiEntrance: 'Вхід',
				navLiMain: 'Головна',
				navLiMasters: 'Майстри',
				navLiGoods: 'Товари',
				navLiStocks: 'Акції',
				navLiBlog: 'Блог',
				navLiContacts: 'Контакти',
			},
			WhoWeAre: {
				explanation1: 'З першого дня нашими основними принципами роботи стали доброзичливість, чутливе ставлення до кожного клієнта і високий рівень професіоналізму у всіх сферах наданих послуг. З перших секунд вашого перебування в салоні ви зануритеся в атмосферу догляду і доброї волі. Відчуйте себе вільно від повсякденної суєти, відкриваючи нові почуття і задоволення від віртуозної майстерності наших фахівців!',
				explanation2: 'Наші майстри створять справжній шедевр, будь то простий або наймодніший стрижка, весілля або вечірнє укладання – все це та інший виглядатимуть не тільки досконалим, але і природним! Для досягнення яскравого кольору і красивих зачісок ми приділяємо велику увагу здоров\'ю волосся, проведення процедур лікування шкіри голови та відновлення шкіри за унікальними методами.',
				explanation3: 'Шкіра рук і ніг допоможе вам зробити останні дотики. Ми можемо зробити не тільки класичний і європейський манікюр і педикюр (включаючи апаратне забезпечення), але і спа-манікюр, який також пропонується чоловікам.',
			},
			WhatWeDo: {
				section1: 'Наші послуги',
				label1: 'Дізнайтеся більше...',
				title1: 'Перукарські послуги',
				title2: 'Манікюр',
				title3: 'Педикюр',
				title4: 'Косметологія',
				title5: 'Естет із тіла',
				title6: 'SPA послуги',
			},
			WhatWeDoDetail: {
				explanation: 'У нас є багато різних послуг в асортименті - якщо ви хочете зареєструватися на консультацію по номерах або електронній пошті, наданих в шапці сайту',
			},
			WhatWeDoDetailBlock: {
				subtitle1: 'Тонування сивини',
				subtitle2: 'Ламінування волосся',
				subtitle3: 'Корекція кольору волосся',
				subtitle4: 'Стрижка волосся',
				subtitle21: 'Манікюр класичний',
				subtitle22: 'Манікюр апаратний',
				subtitle23: 'Манікюр європейський',
				subtitle24: 'Манікюр SPA',
				subtitle31: 'Педикюр класичний',
				subtitle32: 'Комбінований педикюр',
				subtitle33: 'Видалення мозолів',
				subtitle34: 'Педикюр SPA',
				subtitle41: 'Мезотерапія обличчя',
				subtitle42: 'Біоревіталізація',
				subtitle43: 'Ін’єкції ботулотоксину',
				subtitle44: 'Мезотерапія волосся',
				subtitle51: 'Стоун масаж (60 хв)',
				subtitle52: 'Класичний масаж',
				subtitle53: 'Лікувальний масаж',
				subtitle54: 'Антицелюлітний масаж',
				subtitle61: 'Віскі-сповивання',
				subtitle62: 'Пілінг тіла',
				subtitle63: 'Обгортання “Шоколадна акварель”',
				subtitle64: 'Антицелюлітне обгортання',
				subSubTitle1: 'Якщо раніше вам доводилося миритися із сивиною або повністю тонувати все волосся, то сьогодні цього можна уникнути. Сучасні техніки фарбування волосся дають змогу домогтися природних переходів, що імітують натуральні відтінки. Наш салон пропонує приховане чоловіче фарбування і камуфлювання сивини.',
				subSubTitle2: 'Моментально зробити тьмяне, посічене і слабке волосся блискучим, сильним і гладким - це реальність, що стала можливою завдяки ламінуванню. Ця техніка творить справжнє диво! Вона дає змогу реанімувати і покращити зовнішній вигляд волосся всього за одну процедуру. Зробити ламінування волосся в Києві за світовими стандартами можна в салонах краси Kika-Style. Ми гарантуємо результат і його довговічність.',
				subSubTitle3: 'Все, що красиво в житті вимагає турботи і уваги, а з точки зору догляду і догляду, це завдання може бути довірено нам. Мережа салонів краси в Києві допоможе зберегти здоров/\'я волосся завдяки кваліфікованим майстрам, які будуть раді надати вам догляд, стрижку, чистий колiр.',
				subSubTitle4: 'Техніка стрижки не існує як така. Вона має на меті - досягнення результату. Ми не хочемо викликати негативних емоцій у гостей салону. Дискутуємо з приводу бажаної форми, питаємо думку, вивчаємо звички та стиль. Наприклад, дівчина вперше приходить до майстра. Стиліст звертає увагу, в чому одягнена гостя, як лежить її волосся в момент, коли вона тільки прийшла. У розмові майстер дізнається більше, аналізує отриману інформацію, оцінює стан, структуру, колір волосся. Можливо, звичайний стиль гості відрізняється. Зараз вона має довіритися майстру, а майстер хоче виправдати очікування.',
				subSubTitle21: 'Класичний манікюр або, як його називають, вважається одним з найпопулярніших видів манікюру в Києві і Україні. У процесі кутикули і суміжних бічних роликів видаляються з росту за допомогою різання інструментів - ножиці або шматок для кутикули.',
				subSubTitle22: 'Манікюр апаратного забезпечення - це техніка манікюру, в якій майстер обробляє кутикулу і нігтьову пластину з фрезерним верстатом і сопла. Машина може завершити всі етапи, від видалення старого покриття до шліфування кутикули.',
				subSubTitle23: 'Європейський манікюр відрізняється від класики тим, що кутикула не вирізана. Його видаляють, як і будь-який манікюр, але у випадку з європейським манікюром, не з ножицями. Хоча сенс манікюру як такого залишився, тобто догляд за нігтями і руками, європейський манікюр вважається більш ніжним методом.',
				subSubTitle24: 'SPA - це водоочищення для здоров\'я організму, що проводиться в комплексі. SPA педикюр - це догляд за оздоровленням для ноги, пальців, нігтів, де активно використовуються лазні, трави і масло.',
				subSubTitle31: 'Класичний педикюр - це процедура, яка використовує залізо інструменти для обрізання надлишкової шкіри навколо нігтів, а товста, суха шкіра на нозі видаляється спеціальними пілісами.',
				subSubTitle32: 'Комбінований педикюр - це набір апаратних і ручних методів обробки шкіри нігтів і нігтьових пластин. У цій формі педикюр обробляється вручну, а стопа і пальці обробляються за допомогою обертових насадок спеціальної машини.',
				subSubTitle33: 'Видалення мозолів скальпелем — це класичний метод видалення великих сухих мозолів та глибоких стрижневих мозолів на стопах і пальцях ніг. Процедура проводиться під місцевим наркозом та займає до 1 години. Реабілітаційний період триває 7-10 днів, а для досягнення результату, як правило, достатньо одного сеансу.',
				subSubTitle34: 'SPA - це водоочищення для здоров\'я організму, що проводиться в комплексі. SPA педикюр - це догляд за оздоровленням для ноги, пальців, нігтів, де активно використовуються лазні, трави і масло.',
				subSubTitle41: 'Мезотерапія обличчя – малоінвазивна процедура, при якій комплекс корисних мінералів і амінокислот доставляється в мезодерму шляхом ін’єкцій. Ціна вказана від ... і може збільшитися в залежності від того, який препарат ви вибираєте і скільки процедур ви хочете зробити.',
				subSubTitle42: 'Біоревіталізація – процедура ін’єкційного або безін’єкційного введення гіалуронової кислоти під шкіру.  Ціна вказана від ... і може збільшитися в залежності від того, який препарат ви вибираєте і скільки процедур ви хочете зробити.',
				subSubTitle43: 'Ін’єкції ботокса – найбільш ефективна і затребувана косметологічна процедура омолодження шкіри обличчя і боротьби з мімічними зморшками.  Ціна вказана від ... і може збільшитися в залежності від того, який препарат ви вибираєте і скільки процедур ви хочете зробити.',
				subSubTitle44: 'Скажи стоп надмірному випадінню, ламкості волосся і посіченим кінчикам!  Ціна вказана від ... і може збільшитися в залежності від того, який препарат ви вибираєте і скільки процедур ви хочете зробити.',
				subSubTitle51: 'Стоун-масаж – древня східна техніка, якої кілька тисяч років.',
				subSubTitle52: 'Класичний масаж – один з найсучасніших методів лікування та профілактики багатьох захворювань.',
				subSubTitle53: 'Лікувальний масаж – це одна з найбільш ефективних оздоровчих процедур, що полягає в мануальному впливі на різні ділянки тіла.',
				subSubTitle54: 'Антицелюлітний масаж допомагає зменшити відкладення жиру і вирівняти поверхню шкіри.',
				subSubTitle61: 'Whiskey-shrinking - це процедура пов\'язування, заснована на австрійській косметиці бренду Aromaderm Styx Naturcosmetics. Інтригуюча процедура, яка допомагає в боротьбі із зайвою вагою.',
				subSubTitle62: 'Пілінг тіла – ефективна і дуже приємна процедура, що дозволяє відновити і оздоровити поверхню шкіри.',
				subSubTitle63: 'Шоколадне обгортання вважається кращим і, мабуть, найприємнішим способом позбавиться від целюліту, надати шкірі ніжність і бархатистість, а також омолодити її.',
				subSubTitle64: 'Антицелюлітне обгортання – одна з найбільш затребуваних процедур корекції фігури і боротьби з ефектом «апельсинової кірки».',
			},
		},
	},
	en: {
		translation: {
			Technical: {
				currency: 'uah',
			},
			NavBurger: {
				navLiEntrance: 'Entrance',
				navLiMain: 'Home',
				navLiMasters: 'Masters',
				navLiGoods: 'Goods',
				navLiStocks: 'Stocks',
				navLiBlog: 'Blog',
				navLiContacts: 'Contacts',
			},
			WhoWeAre: {
				explanation1: 'From day one, the basic principles of work have been friendliness, sensitivity to each client and high level of professionalism in all areas of service. From the first seconds of your stay in the salon, you will plunge into an atmosphere of care and good will. Feel free from everyday bustle, opening up new feelings and pleasure from the skill of virtuoso specialists!',
				explanation2: 'Our masterpieces will create a real masterpiece, whether it\'s a simple or fashionable haircut, a wedding or a evening styling - all of this and the other will look not only perfect, but also natural! To achieve bright colour and beautiful hair, we pay great attention to hair health, treat skin and restore the skin through unique methods.',
				explanation3: 'The skin of your hands and legs will help you make the last touches. We can not only classic and European manicure and pedicure (including hardware), but also spa manicure, which is also offered to men.',
			},
			WhatWeDo: {
				section1: 'Our servers',
				label1: 'Learn more...',
				title1: 'Haircare services',
				title2: 'Manicure',
				title3: 'Pedicure',
				title4: 'Cosmetology',
				title5: 'Massage',
				title6: 'SPA',
			},
			WhatWeDoDetail: {
				explanation: 'We have many different services in the range - if you want to register for consultation by numbers or email provided in the site header.',
			},
			WhatWeDoDetailBlock: {
				subtitle1: 'ТTining gray hair',
				subtitle2: 'Hair Lamination',
				subtitle3: 'Correction of hair color',
				subtitle4: 'Hair cutting',
				subtitle21: 'Classic manicure',
				subtitle22: 'Manicure machine',
				subtitle23: 'European manicure',
				subtitle24: 'Manicure SPA',
				subtitle31: 'Classic pedicure',
				subtitle32: 'Pedicure combined',
				subtitle33: 'Removal of calluses',
				subtitle34: 'Pedicure SPA',
				subtitle41: 'Face Mesotherapy',
				subtitle42: 'Biorevitalization',
				subtitle43: 'Injections of botulinum toxin',
				subtitle44: 'Mesotherapy of hair',
				subtitle51: 'Stone Massage (60 min)',
				subtitle52: 'Classic massage',
				subtitle53: 'Medical massage',
				subtitle54: 'Anticellulite massage',
				subtitle61: 'Whiskey body wrapping ',
				subtitle62: 'Body Peeling',
				subtitle63: 'Wrap “Chocolate softness”',
				subtitle64: 'Anti-cellulite wrap',
				subSubTitle1: 'If you used to put up with gray or to tone all your hair completely, today you can avoid this. Modern hair staining techniques allow for natural transitions that mimic natural shades. Our salon offers hidden male colour and gray camouflation.',
				subSubTitle2: 'Making dim, secular and weak hair brilliant, strong and smooth at a time is a reality made possible by lamination. This technique is a miracle! It allows resuscitation and improvement of hair appearance in just one procedure. Hair Lamination in Kiev is possible in Kika-Style beauty salons. We guarantee the result and its durability.',
				subSubTitle3: 'Everything that is beautiful in life requires care and attention, and in terms of care and care, this task can be entrusted to us. The Network of Beauty Salons in Kiev will help to maintain hair health thanks to skilled masters who will be happy to provide you with care, haircut, clean color.',
				subSubTitle4: 'The haircut technique does not exist by itself. It aims to achieve results. We do not want to cause negative emotions to the guests of the salon. We discuss the desired form, ask the opinion, study habits and style. For example, a girl comes to the master for the first time. The Stylist draws attention to the dressing of the guest, how her hair is lying at the time she was only here. In the conversation, the master learns more, analyses the information received, evaluates the condition, structure, color of the hair. Maybe the normal guest style is different. He must now trust the master and the master wants to meet expectations.',
				subSubTitle21: 'Classic manicure or, as it is called, is considered one of the most popular types of manicure in Kiev and Ukraine. In the process of cuticles and adjacent side rollers are removed from growth by cutting tools - scissors or pieces for cuticle.',
				subSubTitle22: 'Machine manicure is a manicure technique in which the master processes cuticle and nail plate with milling machine and nozzle. The machine can complete all stages, from removing the old coating to grinding the cuticle.',
				subSubTitle23: 'The European manicure differs from the classics in that the cuticle is not cut. It is removed, like any manicure, but in the case of the European manicure, not with scissors. Although the meaning of manicure as such remained, that is, nail and hands care, the European manicure is considered to be more gentle method.',
				subSubTitle24: 'SPA is water purification for body health, carried out in the complex. SPA pedicure is care for the healing for the leg, fingers, nails, where baths, herbs and oil are actively used.',
				subSubTitle31: 'Classic pedicure is a procedure that uses iron tools to cut excess skin around the nails, and thick, dry skin on the leg is removed by special pylysis.',
				subSubTitle32: 'Combined pedicure is a set of hardware and manual methods of processing the skin of nails and nail plates. In this form, the pedicure is handled, and the foot and fingers are processed using rotating nozzles of a special machine.',
				subSubTitle33: 'Removing of the crooks with a scalpel is a classic method of removing large dry crooks and deep rod crooks on the feet and toes. The procedure is carried out under local anesthesia and takes up to 1 hour. The rehabilitation period lasts 7-10 days, and to achieve the result, as a rule, one session is enough.',
				subSubTitle34: 'SPA is water purification for body health, carried out in the complex. SPA pedicure is care for the healing for the leg, fingers, nails, where baths, herbs and oil are actively used.',
				subSubTitle41: 'Face Mesotherapy is a minimally invasive procedure in which a complex of useful minerals and amino acids is delivered to the mesoderm by injections. The price is indicated from ... and can increase depending on which drug you choose and how many procedures you want to do.',
				subSubTitle42: 'Biorevitalization – the procedure of injection or non-injection hyaluronic acid under the skin. The price is indicated from ... and can increase depending on which drug you choose and how many procedures you want to do.',
				subSubTitle43: 'Botox injections are the most effective and in demand cosmetological procedure for rejuvenation of the face and fighting facial wrinkles. The price is indicated from ... and can increase depending on which drug you choose and how many procedures you want to do.',
				subSubTitle44: 'Tell the stop excessive falling, hair brittle and split tips! The price is indicated from ... and can increase depending on which drug you choose and how many procedures you want to do.',
				subSubTitle51: 'Stone massage is an ancient oriental technique, which is several thousand years.',
				subSubTitle52: 'Classic massage is one of the most modern methods of treatment and prevention of many diseases.',
				subSubTitle53: 'Medical massage is one of the most effective health procedures, which consists in manual influence on various parts of the body.',
				subSubTitle54: 'Anticellulite massage helps to reduce fat deposits and align the skin surface.',
				subSubTitle61: 'Whiskey-shrinking is a binding procedure based on Austrian cosmetics brand Aromaderm Styx Naturcosmetics. Intriguing procedure that helps in fighting excess weight.',
				subSubTitle62: 'Body peeling is an effective and very pleasant procedure, which allows you to restore and improve the skin surface.',
				subSubTitle63: 'Chocolate wrap is considered the best and, perhaps, the most pleasant way to get rid of cellulite, give the skin tenderness and dumbness, as well as rejuvenate it.',
				subSubTitle64: 'Anticellulite wrap is one of the most popular procedures for correction of the figure and combating the effect of the “orange peel”.',
			},
			
		},
	},
	ru: {
		translation: {
			Technical: {
				currency: 'грн',
			},
			NavBurger: {
				navLiEntrance: 'Вход',
				navLiMain: 'Главная',
				navLiMasters: 'Мастера',
				navLiGoods: 'Товары',
				navLiStocks: 'Акции',
				navLiBlog: 'Блог',
				navLiContacts: 'Контакты',
			},
			WhoWeAre: {
				explanation1: 'С первого дня основными принципами работы были дружелюбность, чувствительность к каждому клиенту и высокий уровень профессионализма во всех сферах предоставляемых услуг. С первых секунд вашего пребывания в салоне вы окунетесь в атмосферу заботы и доброй воли. Чувствуйте себя свободными от повседневной суеты, открывая новые чувства и удовольствие от мастерства виртуозных специалистов!',
				explanation2: 'Наши мастера создадут настоящий шедевр, будь то простой или модный стрижка, свадьба или вечернее укладка - все это и другое будет выглядеть не только идеально, но и естественно! Чтобы достичь яркого цвета и красивых причесок, мы уделяем большое внимание здоровью волос, проводим процедуры лечения кожи и восстанавливаем кожу по уникальным методам.',
				explanation3: 'Кожа рук и ног поможет вам сделать последние штрихи. Мы можем не только классический и европейский маникюр и педикюр (включая аппаратное обеспечение), но и спа-маникюр, который также предлагается мужчинам.',
			},
			WhatWeDo: {
				section1: 'Наши услуги',
				label1: 'Узнайте больше...',
				title1: 'Парикмахерские услуги',
				title2: 'Маникюр',
				title3: 'Педикюр',
				title4: 'Косметология',
				title5: 'Массаж',
				title6: 'SPA услуги',
			},
			WhatWeDoDetail: {
				explanation: 'У нас много различных услуг в диапазоне цен - если вы хотите зарегистрироваться на консультации по номерам или электронной почте, предоставленным в шапке сайта.',
			},
			WhatWeDoDetailBlock: {
				subtitle1: 'Тонирование седины',
				subtitle2: 'Ламинирование волос',
				subtitle3: 'Коррекция цвета волос',
				subtitle4: 'Стрижка волос',
				subtitle21: 'Классический маникюр',
				subtitle22: 'Аппаратный маникюр',
				subtitle23: 'Европейский маникюр',
				subtitle24: 'Маникюр SPA',
				subtitle31: 'Педикюр классический',
				subtitle32: 'Педикюр комбинированный',
				subtitle33: 'Удаление мозолей',
				subtitle34: 'Педикюр SPA',
				subtitle41: 'Мезотерапия лица',
				subtitle42: 'Биоревитализация',
				subtitle43: 'Инъекции ботулотоксина',
				subtitle44: 'Мезотерапия волос',
				subtitle51: 'Stone Массаж (60 мин)',
				subtitle52: 'Классический массаж',
				subtitle53: 'Медицинский массаж',
				subtitle54: 'Антицеллюлитный массаж',
				subtitle61: 'Виски-обвертывание',
				subtitle62: 'Пилинг тела',
				subtitle63: 'Обертывание “Шоколадная акварель”',
				subtitle64: 'Антицеллюлитное обвертывание',
				subSubTitle1: 'Если раньше вам приходилось мириться с сединой или полностью тонировать все волосы, то сегодня этого можно избежать. Современные техники окрашивания волос позволяют добиться естественных переходов, имитирующих натуральные оттенки. Наш салон предлагает скрытую мужскую окраску и камуфлирование седины.',
				subSubTitle2: 'Моментально сделать тусклые, секущиеся и слабые волосы блестящими, сильными и гладкими – это реальность, ставшая возможной благодаря ламинированию. Эта техника творит настоящее чудо! Она позволяет реанимировать и улучшить внешний вид волос всего за одну процедуру. Сделать ламинирование волос в Киеве по мировым стандартам можно в салонах красоты Kika-Style. Мы гарантируем результат и его долговечность.',
				subSubTitle3: 'Все, что красиво в жизни требует заботы и внимания, а с точки зрения ухода и ухода, эта задача может быть вверена нам. Сеть салонов красоты в Киеве поможет сохранить здоровье волос благодаря квалифицированным мастерам, которые будут рады предоставить вам уход, стрижку, чистый цвет.',
				subSubTitle4: 'Техника стрижки не существует сама по себе. Она преследует цель - достижение результата. Мы не хотим вызвать негативные эмоции у гостей салона. Дискутируем по поводу желаемой формы, спрашиваем мнение, изучаем привычки и стиль. К примеру, девушка впервые приходит к мастеру. Стилист обращает внимание, в чем одета гостья, как лежат ее волосы в момент, когда она только пришла. В разговоре мастер узнает больше, анализирует полученную информацию, оценивает состояние, структуру, цвет волос. Может быть, обычный стиль гости отличается. Сейчас он должен довериться мастеру, а мастер хочет оправдать ожидания.',
				subSubTitle21: 'Классический маникюр или, как его называют, считается одним из самых популярных видов маникюра в Киеве и Украине. В процессе кутикулки и соседние боковые ролики удаляются из роста инструментами резки - ножницы или кусочки для кутикулы.',
				subSubTitle22: 'Аппаратный маникюр - это техника маникюра, в которой мастер обрабатывает кутикул и ногтейную пластину с фрезерной машиной и сопла. Машина может завершить все этапы, от удаления старого покрытия до шлифовальной кутикулы.',
				subSubTitle23: 'Европейский маникюр отличается от классики тем, что кутику не вырезают. Он удаляется, как и любой маникюр, но в случае европейского маникюра, а не ножницы. Хотя смысл маникюра как такового оставался, то есть уход за ногтями и руками, европейский маникюр считается более мягким методом.',
				subSubTitle24: 'SPA- очистка воды для здоровья тела, проводимая в комплексе. SPA педикюр - это забота о заживлении ногтей, пальцев, ногтей, где активно используются ванны, травы и масло.',
				subSubTitle31: 'Классический педикюр - это процедура, которая использует железные инструменты для разрезания избыточной кожи вокруг ногтей, а толстая сухая кожа на ноге удаляется специальными пилками.',
				subSubTitle32: 'Комбинированный педикюр - это набор аппаратных и ручных методов обработки кожи ногтей и ногтей. В этой форме педикюр обрабатывается, а нога и пальцы обрабатываются с помощью вращающихся сопла специальной машины.',
				subSubTitle33: 'Удаление мозолей скальпелем - классический метод удаления больших сухих мозолей и глубоких стержней на ногах и пальцах. Процедура проводится под местной анестезией и занимает до 1 часа. Реабилитационный период длится 7-10 дней, и для достижения результата, как правило, достаточно одного сеанса.',
				subSubTitle34: 'SPA - очистка воды для здоровья тела, проводимая в комплексе. SPA педикюр - это забота о заживлении ногтей, пальцев, ногтей, где активно используются ванны, травы и масло.',
				subSubTitle41: 'Мезотерапия лица - это минимально инвазивная процедура, в которой комплекс полезных минералов и аминокислот доставляется в мезодерму путем инъекций. Цена указана из... и может увеличиться в зависимости от того, какой наркотик вы выбираете и сколько процедур вы хотите сделать.',
				subSubTitle42: 'Биоревитализация - процедура инъекции или неинъекционная гилуроновая кислота под кожей. Цена указана из... и может увеличиться в зависимости от того, какой наркотик вы выбираете и сколько процедур вы хотите сделать.',
				subSubTitle43: 'Инъекции ботокса являются наиболее эффективными и востребованными косметологическими процедурами омоложения лица и борьбы с морщинами на лице. Цена указана из... и может увеличиться в зависимости от того, какой наркотик вы выбираете и сколько процедур вы хотите сделать.',
				subSubTitle44: 'Скажи нет чрезмерному выпадению, ломкости и секущимся концам! Цена указана из... и может увеличиться в зависимости от того, какой препарат вы выбираете и сколько процедур вы хотите сделать.',
				subSubTitle51: 'Стоун-массаж - древняя восточная техника, которая насчитывает несколько тысяч лет.',
				subSubTitle52: 'Классический массаж - один из самых современных методов лечения и профилактики многих заболеваний.',
				subSubTitle53: 'Медицинский массаж - одна из наиболее эффективных процедур здравоохранения, которая состоит в ручном воздействии на различные части тела.',
				subSubTitle54: 'Антицелюлитный массаж помогает уменьшить жировые отложения и выровнять поверхность кожи.',
				subSubTitle61: 'Whiskey-shrinking - это обязательная процедура, основанная на австрийском косметическом бренде Aromaderm Styx Naturcosmetics. Интригующая процедура, которая помогает бороться с избыточным весом.',
				subSubTitle62: 'Пилинг для тела - эффективная и очень приятная процедура, которая позволяет восстановить и улучшить поверхность кожи.',
				subSubTitle63: 'Шоколадная обертывание считается лучшим и, возможно, самым приятным способом избавиться от целлюлита, дать коже нежность и глупость, а также омолаживать ее.',
				subSubTitle64: 'Антицеллюлитная обертывание - одна из самых популярных процедур коррекции фигуры и борьбы с эффектом "апельсиновой корки"',
			},
		},
	},
}

export default resources;