const dataItems = [
	{
		id: '1',
		article: '123456789',
		name: 'Безсульфатний шампунь з кератином, 150 мл',
		description: 'La\'dor Keratin LPP Shampoo Шампунь для волосся з кератином безсульфатний, 150 мл - унікальний засіб для салонного догляду за волоссям. Безсульфатний шампунь працює в двох напрямках - дбайливо очищає волосся без участі шкідливих речовин і при цьому насичує локони кератином, відновлюючи їх структуру. Як відомо, кератин - це будівельний матеріал для локонів і при його втраті вони стають ламкими, сухими і тьмяним. Шампунь з кератином заповнює «порожнечі» у волоссі і тим самим реконструює їх. Крім того, відсутність шкідливих сульфатів, парабенів і силіконів в складі продукту сприятливо впливає на здоров\'я локонів. Так, безсульфатний шампунь не піниться так, як звичайний, але не варто цього боятися. Засіб ефективно очищає шкіру голови і волосся, не травмуючи їх. Ще одна перевага кератинового шампуню від La\'dor - він збагачений натуральними амінокислотами, протеїнами шовку та розкішним коктейлем їз різних масел (лаванди, камелії, жожоба, авокадо, Аргана, евкаліпта). Весь цей комплекс корисних речовин робить шампунь не тільки засобом для очищення, а й одним з етапів ефективного лікування волосся.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови і коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
		composition: 'Water, Cocoamidopropyl Betaine, Disodium Laureth Sulfosuccinate, lauramine oxide, Glycerine, Butylene Glycol, TEA-Cocoyl Glutamate, Cocamide DEA, PEG-120 Methyl Glucose Dioleate, PPG-3 Caprylyl Ether, PEG-7 Glyceryl Cocoate, Betaine, Hydroxypropyl Chitosan , Trehalose, Hydrolyzed Wheat Protein, Hydrolized Corn Protein, Hydrolized Soy Protein, Hydrolyzed Silk, Sodium Hyaluronate, Dipropylene Glycol, Zein, Argania Spinosa Kernel Oil, Avocado Oil, Camellia Japonica Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Citric Acid, Polyquaternium-10, Hydroxyacetophenone, Sodium Benzoate, Fragrance.',
		prise: 275,
		image: require("./1g.jpg"),
		alt: 'is top image',
	},
	{
		id: '2',
		article: '123456798',
		name: 'Шампунь для сухого і нормального волосся безсульфатний, 530 мл',
		description: 'La\'dor Keratin LPP Shampoo Шампунь для сухого і нормального волосся безсульфатний, 530 мл - шампунь для професійного догляду за шкірою голови та волоссям, який ви можете використовувати в домашніх умовах. Працює одночасно у двох напрямках - делікатно очищає і відновлює локони. Не містить шкідливі сульфати, парабени й силікони.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
		composition: 'Water, Cocoamidopropyl Betaine, Disodium Laureth Sulfosuccinate, lauramine oxide, Glycerine, Butylene Glycol, TEA-Cocoyl Glutamate, Cocamide DEA, PEG-120 Methyl Glucose Dioleate, PPG-3 Caprylyl Ether, PEG-7 Glyceryl Cocoate, Betaine, Hydroxypropyl Chitosan, Trehalose, Hydrolyzed Wheat Protein, Hydrolized Corn Protein, Hydrolized Soy Protein, Hydrolyzed Silk, Sodium Hyaluronate, Dipropylene Glycol, Zein, Argania Spinosa Kernel Oil, Avocado Oil, Camellia Japonica Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Citric Acid, Polyquaternium- 10, Hydroxyacetophenone, Sodium Benzoate, Fragrance.',
		prise: 699,
		image: require("./2g.jpg"),
		alt: 'is top image',
	},
	{
		id: '3',
		article: '123456978',
		name: 'Філер для волосся відновлюючий, 4*13 мл',
		description: 'Lador Perfect Hair Fill-Up Корейський філер для волосся, 4*13 мл - миттєво повертає пошкодженому волоссю структурну цілісність, еластичність й шовковистість. Отриманий ефект ламінування волосся за якістю не відрізняється від салонного результату. Корейський філер для волосся від Lador моментально проникає всередину волосяного стрижня, згладжує лусочки, заповнює порожнечі та пошкодженні структури, повертає волоссю гладкість і здоровий блиск. Філер нормалізує PH, відновлює волосся, ослаблені фарбуванням і хімічними завивками.',
		forWhat: 'відновлення',
		type: 'філер',
		application: 'вміст ампули змішати з холодною водою в пропорції 1: 1. Використовувати тільки керамічну місткість. Ретельно перемішати рідину і нанести отриманий склад на чисте, сухе волосся по всій довжині. Залишити на 15-20 хвилин. Для кращого ефекту використовувати термошапочку або прогріти феном. Змити теплою водою.',
		composition: ' Alcohol, Propylene Glycol, Cetrimonium Chloride, Benzyl Glycol, Ethylhexylglycerin, Raspberry Ketone, Hydrolyzed Keratin, Hydrolyzed Collagen, Hydrolyzed Silk, Ceramide NP, PEG-12 Dimethicone, Glycerin, Octyldodeceth-20, Octyldodeceth-16, Glyoxyloyl Carbocysteine, Glyoxyloyl Keratin Amino Acids, Butylene Glycol, Phyllanthus Emblica Extract, Polyquaternium-92, Citric Acid, Fragrance',
		prise: 380,
		image: require("./3g.jpg"),
		alt: 'is top image',
	},
	{
		id: '4',
		article: '193456978',
		name: 'Філер для волосся відновлюючий, 13 мл',
		description: 'Lador Perfect Hair Fill-Up Корейський філер для волосся, 13 мл - миттєво повертає пошкодженому волоссю структурну цілісність, еластичність й шовковистість. Отриманий ефект ламінування волосся за якістю не відрізняється від салонного результату. Корейський філер для волосся від Lador моментально проникає всередину волосяного стрижня, згладжує лусочки, заповнює порожнечі та пошкодженні структури, повертає волоссю гладкість і здоровий блиск. Філер нормалізує PH, відновлює волосся, ослаблені фарбуванням і хімічними завивками.',
		forWhat: 'відновлення',
		type: 'філер',
		application: 'вміст ампули змішати з холодною водою в пропорції 1: 1. Використовувати тільки керамічну місткість. Ретельно перемішати рідину і нанести отриманий склад на чисте, сухе волосся по всій довжині. Залишити на 15-20 хвилин. Для кращого ефекту використовувати термошапочку або прогріти феном. Змити теплою водою.',
		composition: ' Alcohol, Propylene Glycol, Cetrimonium Chloride, Benzyl Glycol, Ethylhexylglycerin, Raspberry Ketone, Hydrolyzed Keratin, Hydrolyzed Collagen, Hydrolyzed Silk, Ceramide NP, PEG-12 Dimethicone, Glycerin, Octyldodeceth-20, Octyldodeceth-16, Glyoxyloyl Carbocysteine, Glyoxyloyl Keratin Amino Acids, Butylene Glycol, Phyllanthus Emblica Extract, Polyquaternium-92, Citric Acid, Fragrance',
		prise: 80,
		image: require("./4g.jpg"),
		alt: 'is top image',
	},
	{
		id: '5',
		article: '133456978',
		name: 'Шампунь з амінокислотами, 400 мл',
		description: 'Lador Herbalism Shampoo Шампунь з амінокислотами, 400 мл. Шампунь направлений заспокоює шкіру голови і освіжає її, а також живить пошкоджене волосся. Містить 7 трав’яних екстрактів, які зміцнюють волосся, заспокоюють і оздоровлюють шкіру голови. 20 видів амінокислот працюють на живлення і відновлення пошкодженого волосся. Шампунь не містить силіконів, дарує м’якість і блиск.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'на вологе волосся нанести потрібну кількість шампуню, помасувати, ретельно змити, за потреби повторити.',
		composition: 'water, sodium C14-16 olefinsulfonate, coco-betaine, glycerin, butylene glycol, decyl glucoside, MEA cocamide, caprylhydroxamic acid, methylpropanediol, cinanhuma extract, hydroxypropyltrimonium chloride, guarodium hydroxypropyltrimonium chloride, panthenol, salicylic acid, citric acid, EDTA disodium, niacinamide, ethylhexylglycerin, arginine, leucine, tryptophan, lizin, threonine, methionine, hydride stidine, asparagine, allanine, proline, glutamic acid, glutamine, glycine, valine, phenylalanine, aspartic acid, tyrosine, serine, cystine, rhemania root extract, lycarian dogwood extract, Japanese dioscorea root extract, aquatic plantain bulby extract, coconut porium extract, pivonia root extract, witch hazel leaf extract, sage leaf extract, melisi liquor leaf extract, pepper juice extract, lavender flower extract, hautunii extract, eucalyptus globulus leaf extract, soy bean extract.',
		prise: 699,
		image: require("./5g.jpg"),
		alt: 'is top image',
	},
	{
		id: '6',
		article: '133486978',
		name: 'Шампунь для волосся на основі трав\'яних екстрактів, 150 мл',
		description: 'Lador Herbalism Shampoo Шампунь для волосся на основі трав\'яних екстрактів, 150 мл - відмінний продукт для глибокого очищення і зволоження шкіри голови та волосся. 7 трав\'яних екстрактів в основі складу зміцнюють волосяні цибулини, стимулюють кровообіг шкіри голови, живлять волосся корисними мікроелементами. 20 видів амінокислот живлять волосся, відновлюють пошкоджену структуру. Професійний догляд за волоссям це завжди відмінний вибір, тому що результат після застосування завжди відповідає вашим очікуванням.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанести засіб на корені волосся, легкими, масажними рухами розтерти по шкірі голови, змити теплою водою.',
		composition: 'Water, Sodium C14-16 Olefinsulfonate, Coco-Betaine, Glycerin, Butylene Glycol, Decyl Glucoside, MEA Cocamide, Caprilhydroxamic Acid, Methylpropanediol, Cinanhuma Extract, Hydroxypropyltriol Guaric Hydroxypropyltrimonium Chloride, Panthenol, Salicylic Acid, Citric Acid, Sodium EDTA, Niacinamide, Ethylhexylglycerin, Arginine, Leucine, Tryptophan, Lizine, Isoleucine, Threionine Methionine, Histidine, Asparagine, Alanine, Proline, Glutamic Acid, Glutamine, Glycine, Valine, Phenylalanine, Aspartic Acid, Tyrosine, Serine, Cystine, Root Extract, Likarsky Dogwood Extract, Japanese Dioskor Root Extract, Water Plantain Bulby Extract, Coconut Leek Extract, Pivonia Root Extract, Hamamelis Listieu Extract, Sage Leaf Extract, Sage Extract.',
		prise: 305,
		image: require("./6g.jpg"),
		alt: 'is top image',
	},
	{
		id: '7',
		article: '123486978',
		name: 'Маска для волосся на основі трав\'яних екстрактів, 360 мл',
		description: 'Lador Herbalism Treatment Маска для волосся на основі трав\'яних екстрактів, 360 мл - відмінний продукт для відновлення і зволоження волосся від впливу агресивних факторів зовнішнього середовища. Маска розрахована на глибоке живлення і зволоження. 7 трав\'яних екстрактів в основі складу зміцнюють волосяні цибулини, стимулюють кровообіг шкіри голови, живлять волосся корисними мікроелементами. 20 видів амінокислот живлять волосся, відновлюють пошкоджену структуру. Молочна кислота відновить мікрофлору шкіри голови, стимулює ріст волосся.',
		forWhat: 'зволоження і живлення',
		type: 'маска',
		application: 'нанести засіб на чисте вологе волосся, потримати 10-15 хвилин, потім змити теплою водою.',
		composition: 'Water, Sodium C14-16 Olefinsulfonate, Coco-Betaine, Glycerin, Butylene Glycol, Decyl Glucoside, MEA Cocamide, Caprilhydroxamic Acid, Methylpropanediol, Cinanhuma Extract, Hydroxypropyltriol Guaric Hydroxypropyltrimonium Chloride, Panthenol, Salicylic Acid, Citric Acid, Sodium EDTA, Niacinamide, Ethylhexylglycerin, Arginine, Leucine, Tryptophan, Lizine, Isoleucine, Threionine Methionine.',
		prise: 865,
		image: require("./7g.jpg"),
		alt: 'is top image',
	},
	{
		id: '8',
		article: '123486998',
		name: 'Маска для волосся на основі трав\'яних екстрактів, 150 мл',
		description: 'Lador Herbalism Treatment Маска для волосся на основі трав\'яних екстрактів, 150 мл - відмінний продукт для відновлення і зволоження волосся від впливу агресивних факторів зовнішнього середовища. Маска розрахована на глибоке живлення і зволоження. 7 трав\'яних екстрактів в основі складу зміцнюють волосяні цибулини, стимулюють кровообіг шкіри голови, живлять волосся корисними мікроелементами. 20 видів амінокислот живлять волосся, відновлюють пошкоджену структуру. Молочна кислота відновить мікрофлору шкіри голови, стимулює ріст волосся.',
		forWhat: 'зволоження і живлення',
		type: 'маска',
		application: 'нанести засіб на чисте вологе волосся, потримати 10-15 хвилин, потім змити теплою водою.',
		composition: 'Water, cethearilovi alcohol, Propipringle, Amnopropy Dimethicon, C13-15 Alcana, Steatrimoni Chlorid, Dimethicon, Cetrimoni Chlorid, Cetylovius Alcohol, Stearamid Ekstrak Ekhpertil Dimetiliye-7, Amodinniytni Vinograd, Oil Nasiynni Vinograd, Oil Kotrok of Argan, Glizeril Ekrak Eviye ',
		prise: 389,
		image: require("./8g.jpg"),
		alt: 'is top image',
	},
	{
		id: '9',
		article: '123466998',
		name: 'Бальзам для пошкодженого волосся з протеїнами шовку, 200 мл',
		description: 'La\'dor Wonder Balm Бальзам для пошкодженого волосся з протеїнами шовку, 200 мл - ефективний засіб для професійного догляду за волоссям від люксового корейського бренду. Експрес-бальзаму знадобиться менше ніж хвилину, щоб зволожити волосся від коренів до кінчиків і помітно перетворити їх. Його можна застосовувати як SOS-засіб перед важливими заходами, при сильному пошкодженні локонів і на постійній основі в якості одного з етапів догляду. ',
		forWhat: 'зволоження і живлення',
		type: 'бальзам',
		application: 'для експрес-догляду нанесіть невелику кількість кондиціонера на попередньо вимите волосся, відступаючи від кореня. Залиште на волоссі на 1 хвилину і змийте теплою водою. Для інтенсивного впливу бальзам можна залишати на 5-10 хвилин. Використовувати 1-2 рази в тиждень.',
		composition: 'Water, Hydrolyzed Silk, Cetearyl Alcohol, Butylene Glycol, Propylene Glycol, Glycerin, Behentrimonium Chloride, Dimethicone, Macadamia Ternifolia Seed Oil, Phytantriol, Aloe Barbadensis Leaf Extract, Ceramide NP, Sodium Benzoate, Arginine, Leucine, Tryptophan, Lysine, Isoleucine, Threonine, Methionine, Histidine, Asparagine, Alanine, Proline, Glutamic Acid, Glutamine, Glycine, Valine, Phenylalanine, Aspartic Acid, Tyrosine, Serine, Cystine, Benzyl Benzoate, Benzyl Salicylate, Citronellol, Geraniol, Hexyl Cinnamal, Limonene, Linalool, Fragrance\n' +
			'\n',
		prise: 735,
		image: require("./9g.jpg"),
		alt: 'is top image',
	},
	{
		id: '10',
		article: '113466998',
		name: 'Бальзам-маска для волосся з протеїнами шовку, 250 мл',
		description: 'La\'dor Wonder Tear Бальзам-маска для волосся з протеїнами шовку, 250 мл - універсальний засіб для локонів, що працює відразу в трьох напрямках: зміцнює волосся, зволожує їх і надає їм помітний об\'єм. Бальзам-маска не вимагає довгих маніпуляцій і може значно поліпшити стан волосся менше ніж за 1 хвилину. Варто зазначити, що цей продукт застосовують для професійного догляду, тому ви можете отримати ефект справжньої салонної процедури в домашніх умовах. \n' +
			'\n',
		forWhat: 'зволоження і живлення',
		type: 'маска',
		application: 'для експрес-догляду нанесіть невелику кількість продукту на попередньо вимите волосся, відступаючи від кореня. Залиште на волоссі на 1 хвилину і змийте теплою водою. Для інтенсивного впливу бальзам-маску можна залишати на 5-10 хвилин. Використовувати 1-2 рази в тиждень.',
		composition: 'Water, Dimethicone, Cetearyl Alcohol, Behentrimonium Chloride, Butylene Glycol, Propylene Glycol, Amodimethicone, C12-14 Sec-Pareth-7, Hydrolyzed Silk, Aloe Barbadensis Leaf Extract, Ceramide NP, Arginine, Leucine, Tryptophan, Lysine, Isoleucine, Threonine, Methionine, Histidine, Asparagine, Alanine, Proline, Glutamic Acid, Glutamine, Glycine, Valine, Phenylalanine, Aspartic Acid, Tyrosine, Serine, Cystine, Benzyl Benzoate, Benzyl Salicylate, Hexyl Cinnamal, Linalool, Fragrance\n' +
			'\n',
		prise: 849,
		image: require("./10g.jpg"),
		alt: 'is top image',
	},
	{
		id: '11',
		article: '113496998',
		name: 'Шампунь проти випадіння з ментолом для всіх типів волосся, 530 мл',
		description: 'La\'dor Dermatical Hair Loss Shampoo Шампунь проти випадіння з ментолом для всіх типів волосся, 530 мл - професійний засіб від всесвітньо відомого корейського бренду відмінно заспокоює шкіру голови та очищає волосся. Головна мета шампуню - боротьба з надмірним випаданням локонів і стимуляція їх зростання. Шампунь не містить сульфатів, силіконів, штучних барвників, ароматизаторів і має нейтральний pH. Особливий бонус - шампунь дає холодок, освіжає і смачно пахне цитрусами.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити',
		composition: 'Water, Lauryl Glucoside, Decyl Glucoside, Cocodimonium Hydroxypropyl Hydrolyzed Wheat Protein Polyquaternium-10, Disodium Cocoyl Glutamate, Sodium Cocoyl Glutamate, L-Menthol, Salicylic Acid, Dexpanthenol, 1,2-Hexanediol, Propylene Glycol, Hyaluronic Acid, Citrus Aurantium Dulcis (Orange) Oil, Lavandula Angustifolia (Lavender) Oil, Cymbopogon Schoenanthus Oil, Abies Sibirica Oil, Amyris Balsamifera Bark Oil, Salvia Sclarea (Clary) Oil, Sophora Flavescens Root Extract, Capsicum Annuum Fruit Extract, Lycium Chinense Fruit Extract',
		prise: 999,
		image: require("./11g.jpg"),
		alt: 'is top image',
	},
	{
		id: '12',
		article: '113496999',
		name: 'Кондиціонер для сухого та пошкодженого волосся зволожуючий без силіконів, 530 мл',
		description: 'La\'dor Moisture Balancing Conditioner Кондиціонер для сухого та пошкодженого волосся зволожуючий без силіконів, 530 мл - професійний засіб для інтенсивного зволоження сухого та ламкого волосся, пошкоджених фарбуваннями і укладаннями. Кондиціонер збагачений комплексом натуральних інгредієнтів і не містить шкідливих силіконів.',
		forWhat: 'зволоження і живлення',
		type: 'кондиціонер',
		application: 'нанесіть невелику кількість кондиціонера на попередньо вимите волосся, відступаючи від кореня. Залиште на волоссі на кілька хвилин. Змийте теплою водою.',
		composition: 'Water, Cetearyl Alcohol, Behenyl Trimethyl Ammonium Chloride, Paraffin Wax,Glycerin, PPG-3 Caprylyl Ether, Butylene Glycol, Saponaria Officinalis Leaf Extract, Lavandula Angustifolia (Lavender) Flower Extract, Monarda Didyma Leaf Extract, Mentha Piperita (Peppermint) Leaf Extract',
		prise: 609,
		image: require("./12g.jpg"),
		alt: 'is top image',
	},
	{
		id: '13',
		article: '123496999',
		name: 'Шампунь для сухого волосся органічний безсульфатний, 530 мл',
		description: 'La\'dor Triplex Natural Shampoo Шампунь для сухого волосся органічний безсульфатний, 530 мл - професійний шампунь, дбайливо очищає без застосування агресивних і шкідливих компонентів. Тільки натуральний миючі інгредієнти та корисні олії в складі. Продукт не викликає подразнень, не сушить, не сплутує волосся і підходить для чутливої ​​шкіри голови. Формула шампуню містить олії лаванди та чайного дерева, екстракт лимона і куркуму, які мають антибактеріальну властивості, живлять і зволожують волосся, роблять їх слухняними та блискучими. Рослинні компоненти знімають свербіж, усувають лупу і нормалізують кислотно-лужний баланс. Засіб не містить шкідливі сульфати, парабени й силікони',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
		composition: 'Water, Lauryl Glucoside, Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, TEA-Cocoyl Glutamate, Sodium Chloride, Citric Acid, Hydroxyacetophenone, Polyquaternium-7, Polyquaternium-10, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Olea Europaea (Olive) Fruit Oil, Ribes Nigrum (Black Currant) Leaf Extract, Curcuma Longa (Turmeric) Root Extract, Zanthoxylum Schinifolium Leaf Extract, Pulsatilla Koreana Extract',
		prise: 789,
		image: require("./13g.jpg"),
		alt: 'is top image',
	},
	{
		id: '14',
		article: '123496499',
		name: 'Маска для екстра-відновлення пошкодженого волосся колагенова, 150 мл',
		description: 'La\'dor Eco Hydro LPP Treatment Маска для екстра-відновлення пошкодженого волосся колагенова, 150 мл - маска, створена для реанімації сухого і пошкодженого волосся після фарбувань і хімзавивок. Швидко, навіть з першого застосування, живить волосся, прибирає ламкість і тьмяність, робить їх м\'якими та блискучим як шовк. Варто зазначити, що цей продукт відноситься до професійних і є повноцінним салонним доглядом в домашніх умовах. В основі маски - колаген, який швидко робить локони пружними, усуває сухість і ефективно бореться з посічені кінчиками. Доповнено засіб екстрактом моркви, зміцнює волосяні фолікули та маслами жожоба й оливи, які наповнюють їх вітамінами.',
		forWhat: 'зволоження і живлення',
		type: 'маска',
		application: 'нанесіть невелику кількість маски на попередньо вимите волосся, відступаючи від кореня. Залиште на волоссі на кілька хвилин. Змийте теплою водою.',
		composition: 'Water, Cetearyl Alcohol, Benzyl Alcohol, Olea Europaea (Olive) Fruit Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Oleyl Alcohol, Daucus Carota Sativa (Carrot) Root Extract, Stearamidopropyl Dimethylamine, Citric Acid, Lactic Acid, Benzophenone-9, Hydrolyzed Collagen, C12-18 Dialkyldimonium Chloride, Panthenol, Benzyl Glycol, Ethylhexylglycerin, Raspberry Ketone, Glycerin, Octyldodeceth-20, Octyldodeceth-16, Fragrance, Benzyl Salicylate, Cinnamyl Alcohol, Citronellol, Geraniol, Hexyl Cinnamal, Hydroxycitronellal',
		prise: 249,
		image: require("./14g.jpg"),
		alt: 'is top image',
	},
	{
		id: '15',
		article: '123496419',
		name: 'Шампунь для сухого і пошкодженого волосся зволожуючий без силіконів, 530 мл',
		description: 'La\'dor Moisture Balancing Shampoo Шампунь для сухого і пошкодженого волосся зволожуючий без силіконів, 530 мл - професійний засіб для догляду за волоссям та шкірою голови від люксовго корейського бренду не містить шкідливих силіконів, захищає локони та надає могутню антиоксидантну дію. Продукт підходить для частого використання і відмінно тонізує шкіру голови та промиває волосся, не пересушує їх. Рекомендуємо застосовувати шампунь в комплексі з іншими продуктами від La\'dor.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
		composition: 'Water, Sodium Laureth Sulfate, Sodium Lauryl Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Cocamide MEA, Glycol Distearate, Polyquaternium-10, Sodium Benzoate, Hydroxyacetophenone, Piroctone Olamine, Disodium EDTA, Citric Acid, PPG-3 Caprylyl Ether, Quaternium-80, Polyquaternium-7, Saponaria Officinalis Leaf Extract, Butylene Glycol, Acrylamidopropyltrimonium Chloride/Acrylamide Copolymer, Propylene Glycol, Lavandula Angustifolia (Lavender) Flower Extract, Monarda Didyma Leaf Extract, Mentha Piperita (Peppermint) Leaf Extract, Freesia Refracta Extract, Chamomilla Recutita (Matricaria) Flower Extract, Rosmarinus Officinalis (Rosemary) Leaf Extract, 1,2-Hexanediol, Ethylhexylglycerin, Fragrance, Alpha-Isomethyl Ionone, Citronellol, Hexyl Cinnamal',
		prise: 576,
		image: require("./15g.jpg"),
		alt: 'is top image',
	},
	{
		id: '16',
		article: '123496419',
		name: 'Шампунь для сухого і пошкодженого волосся безлужний, 900 мл',
		description: 'La\'dor Damage Protector Acid Shampoo Шампунь для сухого і пошкодженого волосся безлужний, 900 мл - особливий шампунь з pH 4,5, який делікатно очищає шкіру голови та волосся, не травмуючи їх, усуває лупу і запобігає її появі, бореться з сухістю, ламкістю й тьмяністю локонів. У чому переваги беслужного шампуню? Секрет полягає в тому, що наше волосся і шкіра голови люблять слабокислу середу якраз на рівні pH 4-4,5, а більшість доглядових засобів на ринку сильно перевищують цей рівень (pH 6-8), тим самим завдаючи шкоду локонам і шкірі. Тому шампунь від La\'dor не тільки ефективно очищає, але і відновлює кислотно-лужний баланс шкіри голови й перешкоджає вимиванню кортекса (матеріал, з яких складається волосся). У складі засобу також є масло аргана, яке насичується волосся, робить їх м\'якими та слухняними',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте піну великою кількістю теплої води. Процедуру можна повторити. Пам\'ятайте, що шампунь не потрібно наносити на всю довжину волосся, а тільки на корені',
		composition: 'Water, sodium Laureth Sulfate, Cocamidopropyl Betaine, Lauramide DEA, sodium Lauryl Sulfate, Argania spinosa Kernel oil, Disodium EDTA, Polyquaternium-10, Citric Acid, Climbazole, Sodium Benzoate, Phenoxyethanol, Cl 19140, fragrance',
		prise: 699,
		image: require("./16g.jpg"),
		alt: 'is top image',
	},
	{
		id: '17',
		article: '123496411',
		name: 'Шампунь для тонкого і пошкодженого волосся органічний безсульфатний, 150 мл',
		description: 'Lador Triplex Natural Shampoo Шампунь для тонкого і пошкодженого волосся органічний безсульфатний, 150 мл - органічний засіб для догляду за шкірою голови та волоссям, збагачений натуральними компонентами для дбайливого очищення й ефективного зволоження. Формула шампуню не містить шкідливі сульфати, парабени, силікони та при цьому посилено цілим комплексом корисних інгредієнтів: екстракт зеленого чаю, чорна смородина, екстракт червоного перцю, куркума, лимон, лаванда. Всі ці компоненти заспокоюють шкіру голови, усувають лупу, стимулюють ріст волосся і відновлюють здоров\'я локонів, робить їх м\'якими, шовковистим і блискучим. Шампунь має рівень pH-6.0 і підходить для чутливої шкіри голови.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови та коріння волосся, помасажуйте голову і змийте піну великою кількістю теплої води. Процедуру можна повторити. Пам\'ятайте, що шампунь не потрібно наносити на всю довжину волосся, а тільки на корені.',
		composition: 'Water, Lauryl Glucoside, Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, TEA-Cocoyl Glutamate, Polyquaternium-7, Guar Hydroxypropyltrimonium Chloride, Sodium Chloride, Lavandula Angustifolia (Lavender) Oil, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Camellia Sinesis Callus Culture Extract, Ribes Nigrum (Black Currant) Leaf Extract, Curcuma Longa (Turmeric) Root Extract, Citrus Limon (Lemon) Fruit Oil, Zanthoxylum Schinifolium Leaf Extract, Pulsatilla Koreana Extract, Citric Acid',
		prise: 275,
		image: require("./17g.jpg"),
		alt: 'is top image',
	},
	{
		id: '18',
		article: '123496412',
		name: 'Міст для волосся для зміцнення і захисту, 100 мл',
		description: 'La\'dor Wonder Pic Clinic Water PH 4.9 Міст для волосся для зміцнення і захисту, 100 мл - міст у форматі спрею від  корейського бренду працює як незмивний кондиціонер і термозахист, насичує волосся корисними мікроелементами, зміцнює їх і захищає від впливу високих температур. Продукт має pH 4.9, близький нашій шкірі та волоссю, тому міст можна використовувати та для чутливої шкіри голови, і для пошкоджених локонів.',
		forWhat: 'відновлення',
		type: 'міст',
		application: 'міст використовується як 5-ий, останній етап догляду за волоссям. Його необхідно струсити перед використанням і наносити на вологе або сухе волосся з відстані 10-15 см. Не потребує змивання. Процедуру можна повторювати протягом дня.',
		composition: 'Hippophae Rhamnoides Fruit Extract, Cyclopentasiloxane, Hydroxypropyltrimonium Hydrolyzed Silk, Dimethicone, Polyquaternium-6, Polyquaternium-53, Dimethiconol, PEG-60 Hydrogenated Castor Oil, Trideceth-10, Caprylic/Capric Triglyceride, Steartrimonium Chloride, Caprylyl Glycol, Polysorbate 60, Lavandula Angustifolia (Lavender) Extract, Rosmarinus Officinalis (Rosemary) Extract, Thymus Vulgaris (Thyme) Extract, Mentha Arvensis Leaf Extract, Borago Officinalis Extract, Salvia Officinalis (Sage) Leaf Extract, Jasminum Officinale (Jasmine) Extract, Anthemis Nobilis Flower Extract, Disodium EDTA, Fragrance, Alpha-Isomethyl Ionone, Limonene, Butylphenyl Methylpropional',
		prise: 415,
		image: require("./18g.jpg"),
		alt: 'is top image',
	},
	{
		id: '19',
		article: '423496412',
		name: 'Філер для волосся відновлюючий, 150 мл',
		description: 'Lador Perfect Hair Fill-Up Філер для волосся живильний, 150 мл - унікальний засіб, який допоможе відновити пошкоджене, ламке волосся. Даний філер не складно використовувати в рутинному догляді, а результат від застосування не змусить себе чекати. Кераміди в складі формули створюють захисний бар\'єр на волоссі, який захищає їх від негативного впливу зовнішніх факторів. Колаген - унікальний компонент, який здатний насичувати та відновлювати пошкоджене волосся, доглядати за шкірою голови. Амінокислоти шовку активно зволожують кожен пошкоджений волосок зсередини, тим самим відновлюючи їх.',
		forWhat: 'зволоження і живлення',
		type: 'філер',
		application: 'змішати в не металевому посуді склад з водою в пропорції 1: 1, нанести на чисте, злегка вологе волосся. Розподілити по всій довжині, особливо на посічені кінчики. Через 20 хвилин змити теплою водою.',
		composition: 'Water, Steartrimonium Chloride, Alcohol, Hydrolyed Keratin, Hydrolyzed Collagen, Hydrolyzed Silk, Ceramide3ceramide NP, Sodium Benzoate, Hydroxyacetophenone, Fragrance.',
		prise: 480,
		image: require("./19g.jpg"),
		alt: 'is top image',
	},
	{
		id: '20',
		article: '523496412',
		name: 'Шампунь проти лупи, 530 мл',
		description: 'La\'dor Anti-Dandruff Shampoo Шампунь проти лупи, 530 мл - забезпечує ніжне і якісне очищення волосся, усуває лупу і причини її виникнення. В основі активної формули косметичного продукту екстракт лакриці, який вбиває шкідливі мікроби та бактерії, насичує шкіру голови вітамінним комплексом, регулює роботу сальних залоз і вироблення себума, запобігає надмірне випадання волосся. Екстракти камелії, дудника, портулаку, багатоквіткового горця, блетілли та смугастого  женьшеню відновлюють пошкоджені ділянки структури локонів, зміцнюють захисний шар, роблячи їх більш м\'якими, блискучими та слухняними. Гідролізований шовк попереджає ламкість, склеює посічені кінчики, захищає від сплутування. Екстракт ментолу покращує мікроциркуляцію крові, живить волосяні цибулини та відповідає за приємний освіжаючий запах засобу. Шампунь не порушує природний кислотно-лужний баланс.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'Нанести шампунь на вологе волосся і шкіру голови, помасажувати протягом 2-3 хвилин, потім змити теплою водою. При необхідності повторити процедуру.',
		composition: 'Water, Sodium C14-16 Olefin Sulfonate, Cocamidopropyl Betaine, Lauryl Glucoside, Glycerine, Lauramide DEA, PPG-3 Caprylyl Ether, Hydrolyzed Keratin, Hydrolyzed Wheat Protein, Panthenol, Butylene Glycol, Glycyrrhiza Glabra (Licorice) Root Extract, Polygonum Multiflorum Root Extract , Camellia Sinensis Leaf Extract, Angelica Gigas Root Extract, Panax Ginseng Root Extract, Portulaca Oleracea Extract, Rheum Palmatum Root Extract, Silkworm Extract, Bletilla Striata Root Extract, Carthamus Tinctorius (Safflower) Flower Extract, Hydroxyacetophenone, Climbazole, Salicylic Acid, Menthol, Citric acid, Dimethyl sulfone, Allantoin, Polyquaternium-10, betaine, Disodium EDTA, Fragrance',
		prise: 570,
		image: require("./20g.jpg"),
		alt: 'is top image',
	},
	{
		id: '21',
		article: '523496412',
		name: 'Набір філерів з кератином',
		description: 'Lador Perfect Hair Fill-Up Набір філерів з кератином - унікальний засіб, який допоможе відновити пошкоджене, ламке волосся. Даний філер не складно використовувати в рутинному догляді, а результат від застосування не змусить себе чекати. Кераміди в складі формули створюють захисний бар\'єр на волоссі, який захищає їх від негативного впливу зовнішніх факторів. Колаген - унікальний компонент, який здатний насичувати та відновлювати пошкоджене волосся, доглядати за шкірою голови. Амінокислоти шовку активно зволожують кожен пошкоджений волосок зсередини, тим самим відновлюючи їх.',
		forWhat: 'зволоження і живлення',
		type: 'філер',
		application: 'змішати в не металевому посуді склад з водою в пропорції 1: 1, нанести на чисте, злегка вологе волосся. Розподілити по всій довжині, особливо на посічені кінчики. Через 20 хвилин змити теплою водою',
		composition: 'Water, Steartrimonium Chloride, Alcohol, Hydrolyed Keratin, Hydrolyzed Collagen, Hydrolyzed Silk, Ceramide3ceramide NP, Sodium Benzoate, Hydroxyacetophenone, Fragrance.',
		prise: 879,
		image: require("./21g.jpg"),
		alt: 'is top image',
	},
	{
		id: '22',
		article: '523492412',
		name: 'Термозахисний спрей для укладки волосся, 100 мл',
		description: 'Lador Thermal Protection Термозахисний спрей для укладки волосся, 100 мл - пом\'якшувальний засіб для відновлення і блиску волосся. Живить і насичує локони від коренів до кінчиків, робить волосся еластичним, пружним, здоровим на вигляд. Використовувати в якості термозахисту при використанні плойки, фена, прасування. Засіб створює легку захисну плівку на волоссі, яка і захищає від теплого впливу гарячих приладів, і від негативних факторів зовнішнього середовища.',
		forWhat: 'термозахист',
		type: 'захист',
		application: 'потрусити балончик перед використанням. Розпилити на волосся на відстані 10-15 см.',
		composition: 'Water, Butylene Glycol, Polyglyceryl-10 Laurate, Hydrolyzed Collagen, Polyglyceryl-4 Laurate, Polyglycerin-3, Benzyl Glycol, Caprylyl/Capryl Glucoside, Silicone Quaternium-22, Quaternium-81, Arginine, PCA, Cetrimonium Chloride, Polyglyceryl-3 Caprate, Dipropylene Glycol, Propylene Glycol, Viola Mandshurica Flower Extract, Gardenia Florida Fruit Extract, Raspberry Ketone, Benzophenone-5, Hydrolyzed Soy Protein, Hydrolyzed Wheat Protein, Hydrolyzed Corn Protein, Aphanothece Sacrum Polysaccharides, Glycine, Serine, Glutamic Acid, Aspartic Acid, Leucine, Alanine, Lysine, Tyrosine, Phenylalanine, Threonine, Proline, Valine, Isoleucine, Histidine, Methionine, Cysteine, Ethylhexylglycerin, 1,2-Hexanediol, Disodium EDTA, Fragrance, Hexyl Cinnamal',
		prise: 515,
		image: require("./22g.jpg"),
		alt: 'is top image',
	},
	{
		id: '23',
		article: '223492412',
		name: 'Шампунь для волосся зволожуючий, 600 мл',
		description: 'Lador Wonder Bubble Shampoo Шампунь для волосся зволожуючий, 600 мл - відмінний засіб для глибокого очищення шкіри голови та збереження вологи. Активний компонент складу - кератин, завдання якого розгладити відкриті лусочки волосся, зробити їх гладенькими на вигляд. Волосся після шампуню, дуже м\'які, слухняні, нагодовані вологою. Підійде для ніжної шкіри голови, особливо вибагливого волосся. Великий об’єм зручний для тривалого використання.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанести засіб на корені волосся, легкими, масажними рухами розтерти по шкірі голови, змити теплою водою',
		composition: 'Water, Sodium Laureth Sulfate, Ammonium Lauryl Sulfate, Cocamidopropyl Betaine, Disodium Cocoamphodiactate, Dimethicone, Glycol Distearate. Cocamide Mea, Polyquaternium07, Dipropylene Glucol, Polyquaternium-10, Guar Hydroxypropyltrimonium Chloride, Hydroxyethyl Urea. Sodium Hyaluronate, Hydrolyzed Keratin, Lawsonia Inermis Extract, Pisim Sativum Yl Hexapeptide-8, Copper Tripeptide-1, Palmitoyl Pentapeptide-4, Tripeptide-1, Hexapeptide-9, Polyglyceryl-10 Laurate, Citric Acid, C12-15 Pareth-3, Aphanothece Sacrum Polysaccharides, Hydroxyacetophenone, Fragrance.',
		prise: 749,
		image: require("./23g.jpg"),
		alt: 'is top image',
	},
	{
		id: '24',
		article: '223492112',
		name: 'Безсульфатний шампунь з кератином, 150 мл',
		description: 'La\'dor Keratin LPP Shampoo Шампунь для волосся з кератином безсульфатний, 150 мл - унікальний засіб для салонного догляду за волоссям. Безсульфатний шампунь працює в двох напрямках - дбайливо очищає волосся без участі шкідливих речовин і при цьому насичує локони кератином, відновлюючи їх структуру. Як відомо, кератин - це будівельний матеріал для локонів і при його втраті вони стають ламкими, сухими і тьмяним. Шампунь з кератином заповнює «порожнечі» у волоссі і тим самим реконструює їх. Крім того, відсутність шкідливих сульфатів, парабенів і силіконів в складі продукту сприятливо впливає на здоров\'я локонів. Так, безсульфатний шампунь не піниться так, як звичайний, але не варто цього боятися. Засіб ефективно очищає шкіру голови і волосся, не травмуючи їх. Ще одна перевага кератинового шампуню від La\'dor - він збагачений натуральними амінокислотами, протеїнами шовку та розкішним коктейлем їз різних масел (лаванди, камелії, жожоба, авокадо, Аргана, евкаліпта). Весь цей комплекс корисних речовин робить шампунь не тільки засобом для очищення, а й одним з етапів ефективного лікування волосся.',
		forWhat: 'очищення',
		type: 'шампунь',
		application: 'нанесіть невелику кількість шампуню на попередньо змочену шкіру голови і коріння волосся, помасажуйте голову і змийте великою кількістю теплої води. Процедуру можна повторити.',
		composition: 'Cocoamidopropyl Betaine, Disodium Laureth Sulfosuccinate, lauramine oxide, Glycerine, Butylene Glycol, TEA-Cocoyl Glutamate, Cocamide DEA, PEG-120 Methyl Glucose Dioleate, PPG-3 Caprylyl Ether, PEG-7 Glyceryl Cocoate, Betaine, Hydroxypropyl Chitosan , Trehalose, Hydrolyzed Wheat Protein, Hydrolized Corn Protein, Hydrolized Soy Protein, Hydrolyzed Silk, Sodium Hyaluronate, Dipropylene Glycol, Zein, Argania Spinosa Kernel Oil, Avocado Oil, Camellia Japonica Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Citric Acid, Polyquaternium-10, Hydroxyacetophenone, Sodium Benzoate, Fragrance.',
		prise: 249,
		image: require("./24g.jpg"),
		alt: 'is top image',
	},
];

export default dataItems;